const focuses = new Map();
focuses.set("Family_focused/Relationships", [
    "Positive Influence",
    "Resilience",
    "Emotion Control",
    "Interpersonal",
    "Good Friend",
    "Emotional Intelligence",
    "Social Awareness",
    "Amiable Love",
    "Alturism",
    "Flexibility",
    "Kindness",
    "Forgiveness",
    "Planning",
    "Patience",
    "Situational Awareness",
    "Respect",
    "Empathy",
    "Psychology",
    "Romance",
    "Control of Desire",
    "Chivalry",
    "Gentleness",
    "Morality",
    "Considerate",
    "Caring",
    "Friendly",
    "Good Natured",
    "Financial Literacy",
    "Joy",
    "Peace",
    "Goodness",
    "Faithfulness",
    "Maturity",
    "Reasonable",
    "Grounded",
    "Communication",
    "Sexual",
    "Service",
    "Harmonious",
    "Agreeable",
    "Appreciation",
    "Leadership",
    "Mentorship",
    "Time Management",
    "Legacy",
    "Sympathetic",
    "Enabler",
    "Humble",
    "Inspiration",
    "Trust",
    "Preseration",
    "Loyalty",
    "Open-mindedness",
    "Generous",
    "Courage",
    "Work Ethic",
    "Provision",
    "Extraspection",
    "Risk Management",
    "Inductive Reasoning",
    "Rhetoric",
    "Moderation",
    "Urgency",
    "Responsive",
    "Presentation",
    "Intimacy"
]);

focuses.set("Accomplishment_focused", [
    "Optimism",
    "Resilience",
    "Assertion",
    "Introspection",
    "Visionary",
    "Self-care",
    "Society",
    "Methodical",
    "Self-control",
    "Planning",
    "Patience",
    "Abstract",
    "Pragmaticism",
    "Analytical",
    "Physical",
    "Retrospective",
    "Innovative",
    "Forward Thinking",
    "Independence",
    "Productive",
    "Problem Solving",
    "Time Management",
    "Meticulous",
    "Strong Will",
    "Thorough",
    "Legacy",
    "Creativity",
    "Deductive Reasoning",
    "Inspiration",
    "Focus",
    "Courage",
    "Systematic",
    "Work Ethic",
    "Inductive Reasoning",
    "Stoicism",
    "Curiosity",
    "Logic",
    "Impervious",
    "Science",
    "Responsive"
]);

focuses.set("Pursuit_of_interests", [
    "Self-awareness",
    "Assertion",
    "Introspection",
    "Self-care",
    "Flexibility",
    "Mindfulness",
    "Self-control",
    "Spontaneity",
    "Psychology",
    "Retrospective",
    "Joy",
    "Independence",
    "Reasonable",
    "Harmonious",
    "Appreciation",
    "Exploration",
    "Creativity",
    "Preservation",
    "Focus",
    "Open-mindedness",
    "Courage",
    "Inductive Reasoning",
    "Stoicism",
    "Curiousity",
    "Moderation",
    "Impervious",
    "Diverse",
    "Responsive"
]);

focuses.set("Scholar_focused", [
    "Self-awareness",
    "Introspection",
    "Visionary",
    "Patience",
    "Abstract",
    "Pragmaticism",
    "Analytical",
    "Retrospective",
    "History",
    "Scholar",
    "Independence",
    "Grounded",
    "Problem Solving",
    "Mentorship",
    "Time Management",
    "Meticulous",
    "Strong Will",
    "Thorough",
    "Creativity",
    "Deductive Reasoning",
    "Focus",
    "Systematic",
    "Work Ethic",
    "Inductive Reasoning",
    "Stoicism",
    "Curiosity",
    "Logic",
    "Science",
    "How or Why"
]);

focuses.set("Career_focused", [
    "Resilience",
    "Emotion Control",
    "Social Network",
    "Self-awareness",
    "Assertion",
    "Self-care",
    "Flexibility",
    "Self-control",
    "Planning",
    "Patience",
    "Pragmaticism",
    "Analytical",
    "Empathy",
    "Psychology",
    "Charisma",
    "Retrospective",
    "Innovative",
    "Financial Literacy",
    "Forward Thinking",
    "Business Knowledge",
    "Matiruity",
    "Performance",
    "Reasonable",
    "Productive",
    "Communication",
    "Harmonious",
    "Problem Solving",
    "Appreciation",
    "Leadership",
    "Mentorship",
    "Time Management",
    "Meticulous",
    "Strong Will",
    "Thorough",
    "Creativity",
    "Enabler",
    "Humble",
    "Inspiration",
    "Trust",
    "Focus",
    "Open-mindedness",
    "Courage",
    "Systematic",
    "Work Ethic",
    "Extraspection",
    "Risk Management",
    "Inductive Reasoning",
    "Deductive Reasoning",
    "Stoicism",
    "Logic",
    "Rhetoric",
    "Moderation",
    "Responsive",
    "Presentation"
]);

focuses.set("Faith_focused", [
    "Positive Influence",
    "Interpersonal",
    "Self-awareness",
    "Introspection",
    "Good Friend",
    "Visonary",
    "Amiable Love",
    "Alturism",
    "Society",
    "Good Deed",
    "Humanitarian",
    "Mindfulness",
    "Kindness",
    "Self-control",
    "Abstract",
    "Analytical",
    "Empathy",
    "Gentleness",
    "Morality",
    "Considerate",
    "Caring",
    "Friendly",
    "Good Natured",
    "Joy",
    "Peace",
    "Faithfulness",
    "History",
    "Grounded",
    "Harmonious",
    "Agreeable",
    "Appreciation",
    "Mentorship",
    "Thorough",
    "Sympathetic",
    "Enabler",
    "Humble",
    "Inspiration",
    "Trust",
    "Loyalty",
    "Open-mindedness",
    "Generous",
    "Provision",
    "Risk Management",
    "Deductive Reasoning",
    "Curiousity",
    "Rhetoric",
    "Transcendant",
    "Moderation",
    "Urgency",
    "Divine/Righteous",
    "Responsive",
    "Spiritual"
]);

focuses.set('Growth_focused', [
    "Optimism",
    "Resilience",
    "Social Network",
    "Interpersonal",
    "Self-awareness",
    "Introspection",
    "Emotional Intelligence",
    "Self-care",
    "Humanitarian",
    "Flexibility",
    "Mindfulness",
    "Kindness",
    "Change",
    "Self-control",
    "Planning",
    "Pragmaticism",
    "Analytical",
    "Empathy",
    "Physical",
    "Morality",
    "Anxiety Control",
    "Retrospective",
    "Love of Challenge",
    "Financial Literacy",
    "Forward Thinking",
    "Goodness",
    "Maturity",
    "Performance",
    "Scholar",
    "Reasonable",
    "Grounded",
    "Productive",
    "Harmonious",
    "Problem Solving",
    "Mentorship",
    "Growth",
    "Strong Will",
    "Exploration",
    "Thorough",
    "Creativity",
    "Humble",
    "Preservation",
    "Focus",
    "Open-mindedness",
    "Courage",
    "Systematic",
    "Work Ethic",
    "Deductive Reasoning",
    "Inductive Reasoning",
    "Stoicism",
    "Curiosity",
    "Logic",
    "Rhetoric",
    "Moderation",
    "Impervious",
    "Diverse",
    "Responsive",
    "How or Why"
]);

focuses.set("Self-expression_focused", [
    "Emotion Control",
    "Socialization",
    "Interpersonal",
    "Self-awareness",
    "Assertion",
    "Good Friend",
    "Self-care",
    "Mindfulness",
    "Situational Awareness",
    "Respect",
    "Abstract",
    "Spontaneity",
    "Empathy",
    "Charisma",
    "Uniqueness",
    "Interesting",
    "Conversationalist",
    "Entertaining",
    "Eloquent",
    "Friendly",
    "Anxiety Control",
    "Joy",
    "Grounded",
    "Communication",
    "Agreeable",
    "Appreciation",
    "Exploration",
    "Creativity",
    "Humble",
    "Inspiration",
    "Trust",
    "Preservation",
    "Open-mindedness",
    "Courage",
    "Extraspection",
    "Curiosity",
    "Rhetoric",
    "Responsive",
    "Presentation"
]);

focuses.set("Service_focused", [
    "Positive Infleunce",
    "Socialization",
    "Amiability",
    "Interpersonal",
    "Good Friend",
    "Emotional Intelligence",
    "Social Awareness",
    "Amiable Love",
    "Alturism",
    "Society",
    "Good Deed",
    "Humanitarian",
    "Flexibility",
    "Kindness",
    "Forgiveness",
    "Respect",
    "Empathy",
    "Charisma",
    "Chivalry",
    "Gentleness",
    "Morality",
    "Considerate",
    "Caring",
    "Friendly",
    "Goodness",
    "Grounded",
    "Communication",
    "Service",
    "Harmonious",
    "Agreeable",
    "Problem Solving",
    "Appreciation",
    "Mentorship",
    "Time Management",
    "Strong Will",
    "Thorough",
    "Legacy",
    "Sympathetic",
    "Enabler",
    "Humble",
    "Inspiration",
    "Trust",
    "Open-mindedness",
    "Generous",
    "Courage",
    "Provision",
    "Extraspection",
    "Risk Management",
    "Inductive Reasoning",
    "Rhetoric",
    "Moderation",
    "Urgency",
    "Impervious",
    "Responsive"
]);

focuses.set("Living_to_fullest_focused", [
    "Optimism",
    "Socialization",
    "Self-awareness",
    "Introspection",
    "Visionary",
    "Self-care",
    "Flexibility",
    "Mindfulness",
    "Change",
    "Abstract",
    "Situational Awareness",
    "Spontaneity",
    "Friendly",
    "Anxiety Control",
    "Forward Thinking",
    "Joy",
    "Peace",
    "Goodness",
    "Performance",
    "Independence",
    "Grounded",
    "Productive",
    "Communication",
    "Harmonious",
    "Appreciation",
    "Mentorship",
    "Strong Will",
    "Exploration",
    "Thorough",
    "Legacy",
    "Creativity",
    "Enabler",
    "Inspiration",
    "Focus",
    "Open-mindedness",
    "Courage",
    "Work Ethic",
    "Extraspection",
    "Inductive Reasoning",
    "Curiosity",
    "Logic",
    "Transcendant",
    "Urgency",
    "Impervious",
    "Diverse"
]);

export {focuses};