//Goals
const goals_list = new Map();
goals_list.set("Financially_Free", [
    "Financial Literacy",
    "Independence",
    "Business Knowledge",
    "Work-ethic",
    "Resourceful",
    "Motivation",
    "Dedication",
    "Proactive",
]);
goals_list.set("Successful", [
    "Success",
    "Work-ethic",
    "Dedication",
    "Love of Challenge",
    "High Standards",
    "Innovative",
]);
goals_list.set("Religious_Follower", [
    "XReligionX",
    "Amiable Love",
    "Humanitarian",
    "Kindness",
    "Fulfillment",
    "Abstract",
    "Transcendant",
    "Divine",
    "Spiritual",
]);
goals_list.set("Find_your_purpose", [
    "Introspection",
    "Self-awareness",
    "Mindset",
    "Purpose",
    "Exploration",
    "Self-worth",
    "Transcendant",
]);

goals_list.set("Strengthen_your_discipline", [
    "Discipline",
    "Methodical",
    "Thoughtful",
    "Pragmatic",
    "Self-control",
    "Dedication",
    "Work-ethic",
]);
goals_list.set("Find_your_purpose", [
    "Introspection",
    "Self-awareness",
    "Mindset",
    "Purpose",
    "Exploration",
    "Self-worth",
    "Transcendant",
]);

goals_list.set("Control_your_mindset", [
    "Mindset",
    "Strongwill",
    "Assertion",
    "Stoicism",
    "Self-control",
    "Emotion Control",
]);

goals_list.set("Learn_how_to_be_social", [
    "Social Awareness",
    "Socialization",
    "Networking",
    "Interpersonal",
    "Empathy",
    "Charisma",
    "Conversationalism",
    "Entertaining",
    "Friendly",
    "Eloquent",
    "Community",
    "Agreeable",
]);

goals_list.set("Learn_to_have_control_of_your_emotions", [
    "Emotion Control",
    "Presentation",
    "Responsive",
    "Preservation",
    "Strong Will",
    "Situational Awareness",
    "Self-awareness",
    "Emotional Intelligence",
    "Thoughtful",
    "Assertive",
    "Mindfulness",
    "Self Control",
    "Patience",
    "Resilience",
]);

goals_list.set("Better_relationships", [
    "Positive Influence",
    "Emotion Control",
    "Interpersonal",
    "Emotional Intelligence",
    "Good Friend",
    "Prioritization",
    "Kindness",
    "Thoughtfulness",
    "Empathetic",
    "Gentle",
    "Caring",
    "Faithful",
    "Communication",
    "Harmonious",
    "Agreeable",
    "Appreciative",
    "Sympathetic",
    "Honest",
    "Loyalty",
    "Proactive",
]);

goals_list.set("Self-sufficient", [
    "Survival",
    "Life Skills",
    "Impervious",
    "Resourceful",
    "Responsible",
    "Discipline",
    "Preservation",
    "Pride",
    "Self-worth",
    "Strong Will",
    "Exploration",
    "Independence",
    "Retrospective",
    "Growth",
    "Mindset",
    "Prioritization",
    "Assertion",
]);

goals_list.set("Time_Management", [
    "Mentality",
    "Introspection",
    "Prioritization",
    "Planning",
    "Thoughtful",
    "Pragmatic",
    "Analytic",
    "Forward-thinking",
    "Reasonable",
    "Time Management",
    "Thorough",
    "Responsible",
    "Flexible",
    "Systematic",
]);

goals_list.set("Diversify_your_skillsets", [
    "Practice",
    "Diversity",
    "Life Skills",
    "Proactive",
    "Learning",
    "Resourceful",
    "Curiosity",
    "Exploration",
    "Growth",
    "Love of Challenge",
    "Interesting",
]);

goals_list.set("Increase_your_status", [
    "Social Network",
    "Visionary",
    "Interesting",
    "Control of Desire",
    "Success",
    "Entertaining",
    "Financial Literacy",
    "Discipline",
    "Passion",
    "Pride",
    "Preservation",
    "Inspiration",
    "Impervious",
    "Presentation",
    "High Standards",
]);

goals_list.set("Create_a_legacy", [
    "Maintenance",
    "Proactive",
    "Impervious",
    "Purpose",
    "Work-ethic",
    "Provision",
    "Inspiration",
    "Success",
    "Legacy",
    "Pride",
    "Dedication",
    "Visionary",
    "Forward Thinking",
    "Prioritization",
    "Positive Influence",
    "Society",
]);

goals_list.set("Become_healthy", [
    "Mentality",
    "Mindfulness",
    "Physical",
    "Performance",
    "Dedication",
    "Fitness and Health",
    "Preservation",
    "Proactive",
    "Life Skills",
]);

goals_list.set("More_education", [
    "Diverse",
    "Memory",
    "Learning",
    "Curiosity",
    "How and Why",
    "Understanding",
    "Scholar",
]);

goals_list.set("More_happiness", [
    "Optimism",
    "Mentality",
    "Emotion Control",
    "Self-awareness",
    "Self-care",
    "Fulfillment",
    "Mindfulness",
    "Self-confidence",
    "Joy",
    "Self-love",
    "Gratitude",
    "Appreciation",
    "Pride",
    "Happiness",
    "Purpoise",
    "Stoicism",
    "Transcendant",
    "Self-worth",
    "Interpersonal",
]);

goals_list.set("Better_mental_health", [
    "Optimism",
    "Mentality",
    "Resilience",
    "Emotion Control",
    "Socialization",
    "Self-awareness",
    "Emotional Intelligence",
    "Self-care",
    "Prioritization",
    "Contrntfulness",
    "Mindfulness",
    "Change",
    "Thoughtful",
    "Psychology",
    "Self-confidence",
    "Anxiety Control",
    "Introspection",
    "Grounded",
    "Self-love",
    "Growth",
    "Self-worth",
    "Perseverence",
    "Stron-will",
    "Pride",
    "Progress",
    "Preservation",
    "Happinness",
    "Courage",
    "Authentic",
    "Stoicism",
    "Transcendant",
    "Proactive",
    "Self-worth",
]);

goals_list.set("Take_control_of_your_life", [
    "Responsive",
    "Maintenance",
    "Life Skills",
    "Proactive",
    "Impervious",
    "Moderation",
    "Resourceful",
    "Stoicism",
    "Risk Management",
    "Purpose",
    "Courage",
    "Focus",
    "Responsible",
    "Responsible",
    "Accountable",
    "Understanding",
    "Strong-will",
    "Perseverance",
    "Problem Solving",
    "Discipline",
    "Independence",
    "Visionary",
    "Situational Awareness",
    "Mindfulness",
    "Contentment",
    "Flexibile",
    "Prioritization",
    "Self-awareness",
    "Introspection",
    "Assertion",
    "Mentality",
]);

goals_list.set("Serve_the_community", [
    "Positive Influence",
    "Socialization",
    "Amiability",
    "Interpersonal",
    "Good Friend",
    "Emotional Intelligence",
    "Social Awareness",
    "Amiable Love",
    "Alturism",
    "Society",
    "Humanitarian",
    "Mindfulness",
    "Kindness",
    "Respect",
    "Empathy",
    "Charisma",
    "Chivalry",
    "Gentleness",
    "Considerate",
    "Caring",
    "Friendly",
    "Good Natured",
    "Joy",
    "Patience",
    "Service",
    "Harmonious",
    "Agreeable",
    "Sympathetic",
    "Enabler",
    "Inspiration",
    "Humble",
    "Generous",
    "Provision",
]);

goals_list.set("Become_self-aware", [
    "Core Values",
    "Ethics",
    "Presentation",
    "Self-worth",
    "Purpose",
    "Authenticity",
    "Accountability",
    "Understanding",
    "Comfort",
    "Self-worth",
    "Virtue",
    "Self-love",
    "Grounded",
    "Anxiety Control",
    "Self-confidence",
    "Psychology",
    "Analytical",
    "Respect",
    "Self-control",
    "Mindset",
    "Self-awareness",
    "Self-care",
    "Introspection",
]);

goals_list.set("Learn_to_be_more_emotional_or_gain_emotional_intelligence", [
    "External Awareness",
    "Information Processing",
    "Understanding",
    "Humble",
    "Harmony",
    "Sympathetic",
    "Leadership",
    "Agreeable",
    "Communication",
    "Good Natured",
    "Friendly",
    "Entertaining",
    "Conversationalist",
    "Interesting",
    "Empathy",
    "Mindfulness",
    "Humanitarian",
    "Social Awareness",
    "Emotional Intelligence",
    "Socialization",
    "Emotion Control",
]);

goals_list.set("Learn_how_to_be_optimistic", [
    "Optimism",
    "Mentality",
    "Resilience",
    "Self-awareness",
    "Visionary",
    "Contentment",
    "Analytical",
    "Psychology",
    "Good Natured",
    "Reasonable",
    "Grounded",
    "Appreciation",
    "Gratefulness",
    "Focus",
    "Open-mindedness",
    "Extraspection",
    "Impervious",
]);

goals_list.set("Learn_to_be_mindful", [
    "Reality",
    "Responsive",
    "External Awareness",
    "Information Processing",
    "Lively",
    "Proactive",
    "Extraspection",
    "Open-mindedness",
    "Grounded",
    "Situational Awareness",
    "Mindfulness",
    "Mindfulness",
    "Mindset",
    "Social Awareness",
    "Self-awareness",
]);

goals_list.set("Learn_to_love_learning", [
    "Mindset",
    "Self-awareness",
    "Introspection",
    "Prioritization",
    "Change",
    "Thoughtful",
    "Retrospective",
    "Innovative",
    "Forward Thinking",
    "Scholar",
    "Dedication",
    "Discipline",
    "Motivation",
    "Growth",
    "Exploration",
    "Progress",
    "Understanding",
    "Focus",
    "Open-mindedness",
    "Courage",
    "Curiosity",
    "Learning",
    "Proactive",
    "How or Why",
]);

goals_list.set("Be_honorable_and_virtuous", [
    "High Standards",
    "Core Values",
    "Self-worth",
    "Divine/Righteous",
    "Impervious",
    "Moderation",
    "Preservation",
    "Strong Will",
    "Virtue",
    "Goodness",
    "Good Natured",
    "Morality",
    "Pragmatic",
    "Respect",
    "Thoughtfulness",
    "Society",
]);

goals_list.set("Be_self-confident", [
    "Mentality",
    "Self-awareness",
    "Assertion",
    "Self-confidence",
    "Charisma",
    "Self-love",
    "Execution",
    "Self-worth",
    "Strong Will",
    "Pride",
    "Courage",
    "Self-worth",
]);

goals_list.set("Learn_to_be_a_leader", [
    "Presentation",
    "Responsive",
    "External Awareness",
    "Proactive",
    "Rhetoric",
    "Inductive Reasoning",
    "Risk Management",
    "Extraspective",
    "Authentic",
    "Honesty",
    "Resonsible",
    "Accountability",
    "Understanding",
    "Trust",
    "Inspiration",
    "Humble",
    "Enabler",
    "Deductive Reasoning",
    "Success",
    "Motivation",
    "Time Management",
    "Mentorship",
    "Leadership",
    "Execution",
    "Agreeable",
    "Harmonious",
    "Communication",
    "Dedication",
    "Business Knowledge",
    "Good Natured",
    "Anxiety Control",
    "Friendly",
    "Eloquent",
    "Caring",
    "Considerate",
    "Ethical",
    "Morality",
    "Charisma",
    "Self-confidence",
    "Psychology",
    "Empathy",
    "Respect",
    "Thoughtful",
    "Planning",
    "Methodical",
    "Flexibility",
    "Prioritization",
    "Social Awareness",
    "Visionary",
    "Emotional",
    "Intelligence",
    "Meticulous",
    "Social Network",
    "Socialization",
    "Emotion Control",
    "Resilience",
    "Optimism",
    "Positive Influence",
]);

goals_list.set("Learn_how_to_think_and_problem_solve", [
    "Self-awareness",
    "Assertion",
    "Introspection",
    "Visionary",
    "Prioritization",
    "Mindset",
    "Flexibility",
    "Creativity",
    "Methodical",
    "Planning",
    "Thoughtful",
    "Abstract",
    "Pragmaticism",
    "Analytical",
    "Retrospective",
    "Innovative",
    "Reasonable",
    "Problem Solving",
    "Deductive Reasoning",
    "Inductive Reasoning",
    "Understanding",
    "Open-mindedness",
    "Extraspection",
    "Curiosity",
    "Logic",
    "Urgency",
    "Proactive",
    "Information Processing",
    "Responsive",
    "How or Why",
]);

goals_list.set("Learn_how_to_be_creative", [
    "Responsive",
    "Diverse",
    "External Awareness",
    "Curiosity",
    "Open-mindedness",
    "Understanding",
    "Trust",
    "Exploration",
    "Independence",
    "Patience",
    "Change",
    "Flexibility",
    "Mindset",
    "Visionary",
    "Spontaneity",
]);

goals_list.set("Learn_how_to_be_flexible", [
    "Introspective",
    "Visionary",
    "Mindset",
    "Flexibility",
    "Change",
    "Thoughtful",
    "Abstract",
    "Uniqueness",
    "Retrospective",
    "Innovative",
    "Forward Thinking",
    "Scholar",
    "Exploration",
    "Creativity",
    "Inductive Reasoning",
    "Open-mindedness",
    "Extraspection",
    "Curiousity",
    "Information Processing",
    "Diverse",
]);

goals_list.set("Learn_how_to_be_responsible_and_accountable", [
    "High Standards",
    "Core Values",
    "Ethics",
    "Maintenance",
    "Moderation",
    "Risk Management",
    "Work Ethic",
    "Authentic",
    "Systematic",
    "Responsible",
    "Accountability",
    "Preservation",
    "Strong Will",
    "Meticulous",
    "Virtue",
    "Traditionalism",
    "Discipline",
    "Maturity",
    "Self-confidence",
    "Assertion",
    "External Awareness",
    "Prioritization",
    "Impervious",
]);

goals_list.set("Find_a_romantic_partner", [
    "Socialization",
    "Amiability",
    "Social Network",
    "Interpersonal",
    "Self-awareness",
    "Emotional Intelligence",
    "Self-care",
    "Social Awareness",
    "Kindness",
    "Patience",
    "Respect",
    "Empathy",
    "Psychological",
    "Physical",
    "Romance",
    "Self-confidence",
    "Charisma",
    "Uniqueness",
    "Control of Desire",
    "Interesting",
    "Chivalry",
    "Gentleness",
    "Considerate",
    "Conversationalist",
    "Caring",
    "Entertaining",
    "Anxiety Control",
    "Good Natured",
    "Performance",
    "COmmunication",
    "Sexual",
    "Aggreable",
    "Passion",
    "Sympathetic",
    "Trust",
    "Comfort",
    "Honesty",
    "Authentic",
    "Proactive",
    "Lively",
    "Aesthetic",
    "Maintenance",
    "Presentation",
    "Intimacy",
]);

goals_list.set("Learn_how_to_be_systematic_and_plan", [
    "External Awareness",
    "Proactive",
    "Deductive Reasoning",
    "Extraspection",
    "Risk Management",
    "Systematic",
    "Responsible",
    "Thorough",
    "Meticulous",
    "Time Management",
    "Discipline",
    "Dedication",
    "Retrospective",
    "Analytical",
    "Abstract",
    "Planning",
    "Methodical",
    "Open-minded",
    "Flexible",
    "Prioritization",
    "Visionary",
]);

goals_list.set("Learn_to_be_charismatic_and_have_a_good_image", [
    "Emotion Control",
    "Socialization",
    "Amiambility",
    "Interpersonal",
    "Self-awareness",
    "Emotional Intelligence",
    "Self-care",
    "Social Awareness",
    "Mindfulness",
    "Empathy",
    "Psychology",
    "Physical",
    "Self-confidence",
    "Charisma",
    "Uniqueness",
    "Interesting",
    "Conversationalist",
    "Eloquent",
    "Entertaining",
    "Friendly",
    "Anxiety Control",
    "Good Natured",
    "Joy",
    "Communication",
    "Agreeable",
    "Sympathetic",
    "Enabler",
    "Humble",
    "Grounded",
    "Retrospective",
    "Thoughtful",
    "Methodical",
    "Change",
    "Mindfulness",
    "Mindset",
    "Visionary",
    "Society",
    "Optimism",
]);

goals_list.set("Help_the_environment", [
    "Core Values",
    "Ethics",
    "Reality",
    "Responsive",
    "Maintenance",
    "Acceptance",
    "Sciences",
    "Proactive",
    "Extraspective",
    "Purpose",
    "Preservation",
    "Inspiration",
    "Progress",
    "Problem Solving",
    "Harmonious",
    "Service",
    "Nature",
    "Dedication",
    "Humble",
    "Grounded",
    "Retrospective",
    "Thoughtful",
    "Methodical",
    "Change",
    "Mindfulness",
    "Mindset",
    "Visionary",
    "Society",
    "Optimism",
]);

goals_list.set("Revolutionize_the_world", [
    "Positive Influence",
    "Optimism",
    "Mentality",
    "Resilience",
    "Impervious",
    "Assertion",
    "Introspection",
    "Visionary",
    "Prioritization",
    "Society",
    "Humanitarian",
    "Fulfillment",
    "Change",
    "Planning",
    "Thoughtful",
    "Abstract",
    "Spontaneity",
    "Pragmaticism",
    "Uniqueness",
    "Morality",
    "Innovative",
    "Modernized",
    "Forward Thinking",
    "Dedication",
    "Discipline",
    "Service",
    "Execution",
    "Motivation",
    "Strong Will",
    "Pride",
    "Progress",
    "Inspiration",
    "Open-minded",
    "Purpose",
    "Impervious",
    "Core Values",
]);

goals_list.set("Accomplish_a_great_feat", [
    "High Standards",
    "Practice",
    "Self-worth",
    "Proactive",
    "Impervious",
    "Memory",
    "Resourceful",
    "Work-ethic",
    "Authentic",
    "Courage",
    "Focus",
    "Pride",
    "Success",
    "Thorough",
    "Strong Will",
    "Growth",
    "Passion",
    "Motivation",
    "Meticulous",
    "Perseverence",
    "Time Management",
    "Execution",
    "Discipline",
    "Dedication",
    "Productive",
    "Performance",
    "Love of Challenge",
    "Innovative",
    "Thoughtful",
    "Mindset",
    "Prioritization",
    "Self-care",
    "Visionary",
    "Introspective",
    "Assertion",
    "Resilience",
    "Optimism",
]);

goals_list.set("Learn_to_be_organized", [
    "Mentality",
    "Self-awareness",
    "Introspection",
    "Self-care",
    "Prioritization",
    "Mindfulness",
    "Methodical",
    "Self-control",
    "Thoughtful",
    "Patience",
    "Situational Awareness",
    "Grounded",
    "Dedication",
    "Discipline",
    "Meticulous",
    "Preservation",
    "Thorough",
    "Accountability",
    "Responsible",
    "Focus",
    "Systematic",
    "Work Ethic",
    "Risk Management",
    "Moderation",
    "Impervious",
    "Lifeskills",
    "External Awareness",
    "Maintenance",
    "Presentation",
    "Practifce",
    "Core Values",
    "High Standards",
]);

export{goals_list};