import promptSync from 'prompt-sync';
const prompt = promptSync();

const output = [];

const goal_list = {
  'Financially free': [
    'Financial Literacy',
    'Independence',
    'Business Knowledge',
    'Work-ethic',
    'Resourceful',
    'Motivation',
    'Dedication',
    'Proactive',
  ],
  Successful: ['Success', 'Work-ethic', 'Dedication', 'Love of Challenge', 'High Standards', 'Innovative'],
  'Religious follower': [
    'XReligionX',
    'Amiable Love',
    'Humanitarian',
    'Kindness',
    'Fulfillment',
    'Abstract',
    'Transcendant',
    'Divine',
    'Spiritual',
  ],
  'Find your purpose': [
    'Introspection',
    'Self-awareness',
    'Mindset',
    'Purpose',
    'Exploration',
    'Self-worth',
    'Transcendant',
  ],
  'Strengthen your discipline': [
    'Discipline',
    'Methodical',
    'Thoughtful',
    'Pragmatic',
    'Self-control',
    'Dedication',
    'Work-ethic',
  ],
  'Control your mindset': ['Mindset', 'Strongwill', 'Assertion', 'Stoicism', 'Self-control', 'Emotion Control'],
  'CLearn how to be social': [
    'Social Awareness',
    'Socialization',
    'Networking',
    'Interpersonal',
    'Empathy',
    'Charisma',
    'Conversationalism',
    'Entertaining',
    'Friendly',
    'Eloquent',
    'Community',
    'Agreeable',
  ],
  'Learn to have control of your emotions': [
    'Emotion Control',
    'Presentation',
    'Responsive',
    'Preservation',
    'Strong Will',
    'Situational Awareness',
    'Self-awareness',
    'Emotional Intelligence',
    'Thoughtful',
    'Assertive',
    'Mindfulness',
    'Self Control',
    'Patience',
    'Resilience',
  ],
  'Better relationships': [
    'Positive Influence',
    'Emotion Control',
    'Interpersonal',
    'Emotional Intelligence',
    'Good Friend',
    'Prioritization',
    'Kindness',
    'Thoughtfulness',
    'Empathetic',
    'Gentle',
    'Caring',
    'Faithful',
    'Communication',
    'Harmonious',
    'Agreeable',
    'Appreciative',
    'Sympathetic',
    'Honest',
    'Loyalty',
    'Proactive',
  ],
  'Self-sufficient': [
    'Survival',
    'Life Skills',
    'Impervious',
    'Resourceful',
    'Responsible',
    'Discipline',
    'Preservation',
    'Pride',
    'Self-worth',
    'Strong Will',
    'Exploration',
    'Independence',
    'Retrospective',
    'Growth',
    'Mindset',
    'Prioritization',
    'Assertion',
  ],
  'Time managment': [
    'Mentality',
    'Introspection',
    'Prioritization',
    'Planning',
    'Thoughtful',
    'Pragmatic',
    'Analytic',
    'Forward-thinking',
    'Reasonable',
    'Time Management',
    'Thorough',
    'Responsible',
    'Flexible',
    'Systematic',
  ],
  'Diversify your skillsets': [
    'Practice',
    'Diversity',
    'Life Skills',
    'Proactive',
    'Learning',
    'Resourceful',
    'Curiosity',
    'Exploration',
    'Growth',
    'Love of Challenge',
    'Interesting',
  ],
  'Increase your status': [
    'Social Network',
    'Visionary',
    'Interesting',
    'Control of Desire',
    'Success',
    'Entertaining',
    'Financial Literacy',
    'Discipline',
    'Passion',
    'Pride',
    'Preservation',
    'Inspiration',
    'Impervious',
    'Presentation',
    'High Standards',
  ],
  'Create a legacy': [
    'Maintenance',
    'Proactive',
    'Impervious',
    'Purpose',
    'Work-ethic',
    'Provision',
    'Inspiration',
    'Success',
    'Legacy',
    'Pride',
    'Dedication',
    'Visionary',
    'Forward Thinking',
    'Prioritization',
    'Positive Influence',
    'Society',
  ],
  'Become healthy': [
    'Mentality',
    'Mindfulness',
    'Physical',
    'Performance',
    'Dedication',
    'Fitness and Health',
    'Preservation',
    'Proactive',
    'Life Skills',
  ],
  'More education': ['Diverse', 'Memory', 'Learning', 'Curiosity', 'How and Why', 'Understanding', 'Scholar'],
  'More happiness': [
    'Optimism',
    'Mentality',
    'Emotion Control',
    'Self-awareness',
    'Self-care',
    'Fulfillment',
    'Mindfulness',
    'Self-confidence',
    'Joy',
    'Self-love',
    'Gratitude',
    'Appreciation',
    'Pride',
    'Happiness',
    'Purpoise',
    'Stoicism',
    'Transcendant',
    'Self-worth',
    'Interpersonal',
  ],
  'Better mental health': [
    'Optimism',
    'Mentality',
    'Resilience',
    'Emotion Control',
    'Socialization',
    'Self-awareness',
    'Emotional Intelligence',
    'Self-care',
    'Prioritization',
    'Contrntfulness',
    'Mindfulness',
    'Change',
    'Thoughtful',
    'Psychology',
    'Self-confidence',
    'Anxiety Control',
    'Introspection',
    'Grounded',
    'Self-love',
    'Growth',
    'Self-worth',
    'Perseverence',
    'Stron-will',
    'Pride',
    'Progress',
    'Preservation',
    'Happinness',
    'Courage',
    'Authentic',
    'Stoicism',
    'Transcendant',
    'Proactive',
    'Self-worth',
  ],
  'Take control of your life': [
    'Responsive',
    'Maintenance',
    'Life Skills',
    'Proactive',
    'Impervious',
    'Moderation',
    'Resourceful',
    'Stoicism',
    'Risk Management',
    'Purpose',
    'Courage',
    'Focus',
    'Responsible',
    'Responsible',
    'Accountable',
    'Understanding',
    'Strong-will',
    'Perseverance',
    'Problem Solving',
    'Discipline',
    'Independence',
    'Visionary',
    'Situational Awareness',
    'Mindfulness',
    'Contentment',
    'Flexibile',
    'Prioritization',
    'Self-awareness',
    'Introspection',
    'Assertion',
    'Mentality',
  ],
  'Serve the community': [
    'Positive Influence',
    'Socialization',
    'Amiability',
    'Interpersonal',
    'Good Friend',
    'Emotional Intelligence',
    'Social Awareness',
    'Amiable Love',
    'Alturism',
    'Society',
    'Humanitarian',
    'Mindfulness',
    'Kindness',
    'Respect',
    'Empathy',
    'Charisma',
    'Chivalry',
    'Gentleness',
    'Considerate',
    'Caring',
    'Friendly',
    'Good Natured',
    'Joy',
    'Patience',
    'Service',
    'Harmonious',
    'Agreeable',
    'Sympathetic',
    'Enabler',
    'Inspiration',
    'Humble',
    'Generous',
    'Provision',
  ],
  'Become self-aware': [
    'Core Values',
    'Ethics',
    'Presentation',
    'Self-worth',
    'Purpose',
    'Authenticity',
    'Accountability',
    'Understanding',
    'Comfort',
    'Self-worth',
    'Virtue',
    'Self-love',
    'Grounded',
    'Anxiety Control',
    'Self-confidence',
    'Psychology',
    'Analytical',
    'Respect',
    'Self-control',
    'Mindset',
    'Self-awareness',
    'Self-care',
    'Introspection',
  ],
  'Learn to be more emotional or gain emotional intelligence': [
    'External Awareness',
    'Information Processing',
    'Understanding',
    'Humble',
    'Harmony',
    'Sympathetic',
    'Leadership',
    'Agreeable',
    'Communication',
    'Good Natured',
    'Friendly',
    'Entertaining',
    'Conversationalist',
    'Interesting',
    'Empathy',
    'Mindfulness',
    'Humanitarian',
    'Social Awareness',
    'Emotional Intelligence',
    'Socialization',
    'Emotion Control',
  ],
  'Learn how to be optimistic': [
    'Optimism',
    'Mentality',
    'Resilience',
    'Self-awareness',
    'Visionary',
    'Contentment',
    'Analytical',
    'Psychology',
    'Good Natured',
    'Reasonable',
    'Grounded',
    'Appreciation',
    'Gratefulness',
    'Focus',
    'Open-mindedness',
    'Extraspection',
    'Impervious',
  ],
  'Learn to be mindful': [
    'Reality',
    'Responsive',
    'External Awareness',
    'Information Processing',
    'Lively',
    'Proactive',
    'Extraspection',
    'Open-mindedness',
    'Grounded',
    'Situational Awareness',
    'Mindfulness',
    'Mindfulness',
    'Mindset',
    'Social Awareness',
    'Self-awareness',
  ],
  'Learn to love learning': [
    'Mindset',
    'Self-awareness',
    'Introspection',
    'Prioritization',
    'Change',
    'Thoughtful',
    'Retrospective',
    'Innovative',
    'Forward Thinking',
    'Scholar',
    'Dedication',
    'Discipline',
    'Motivation',
    'Growth',
    'Exploration',
    'Progress',
    'Understanding',
    'Focus',
    'Open-mindedness',
    'Courage',
    'Curiosity',
    'Learning',
    'Proactive',
    'How or Why',
  ],
  'Be honorable and virtuous': [
    'High Standards',
    'Core Values',
    'Self-worth',
    'Divine/Righteous',
    'Impervious',
    'Moderation',
    'Preservation',
    'Strong Will',
    'Virtue',
    'Goodness',
    'Good Natured',
    'Morality',
    'Pragmatic',
    'Respect',
    'Thoughtfulness',
    'Society',
  ],
  'Be Self-confident': [
    'Mentality',
    'Self-awareness',
    'Assertion',
    'Self-confidence',
    'Charisma',
    'Self-love',
    'Execution',
    'Self-worth',
    'Strong Will',
    'Pride',
    'Courage',
    'Self-worth',
  ],
  'Learn to be a leader': [
    'Presentation',
    'Responsive',
    'External Awareness',
    'Proactive',
    'Rhetoric',
    'Inductive Reasoning',
    'Risk Management',
    'Extraspective',
    'Authentic',
    'Honesty',
    'Resonsible',
    'Accountability',
    'Understanding',
    'Trust',
    'Inspiration',
    'Humble',
    'Enabler',
    'Deductive Reasoning',
    'Success',
    'Motivation',
    'Time Management',
    'Mentorship',
    'Leadership',
    'Execution',
    'Agreeable',
    'Harmonious',
    'Communication',
    'Dedication',
    'Business Knowledge',
    'Good Natured',
    'Anxiety Control',
    'Friendly',
    'Eloquent',
    'Caring',
    'Considerate',
    'Ethical',
    'Morality',
    'Charisma',
    'Self-confidence',
    'Psychology',
    'Empathy',
    'Respect',
    'Thoughtful',
    'Planning',
    'Methodical',
    'Flexibility',
    'Prioritization',
    'Social Awareness',
    'Visionary',
    'Emotional',
    'Intelligence',
    'Meticulous',
    'Social Network',
    'Socialization',
    'Emotion Control',
    'Resilience',
    'Optimism',
    'Positive Influence',
  ],
  'Learn how to think and problem solve': [
    'Self-awareness',
    'Assertion',
    'Introspection',
    'Visionary',
    'Prioritization',
    'Mindset',
    'Flexibility',
    'Creativity',
    'Methodical',
    'Planning',
    'Thoughtful',
    'Abstract',
    'Pragmaticism',
    'Analytical',
    'Retrospective',
    'Innovative',
    'Reasonable',
    'Problem Solving',
    'Deductive Reasoning',
    'Inductive Reasoning',
    'Understanding',
    'Open-mindedness',
    'Extraspection',
    'Curiosity',
    'Logic',
    'Urgency',
    'Proactive',
    'Information Processing',
    'Responsive',
    'How or Why',
  ],
  'Learn how to be creative': [
    'Responsive',
    'Diverse',
    'External Awareness',
    'Curiosity',
    'Open-mindedness',
    'Understanding',
    'Trust',
    'Exploration',
    'Independence',
    'Patience',
    'Change',
    'Flexibility',
    'Mindset',
    'Visionary',
    'Spontaneity',
  ],
  'Learn how to be flexible': [
    'Introspective',
    'Visionary',
    'Mindset',
    'Flexibility',
    'Change',
    'Thoughtful',
    'Abstract',
    'Uniqueness',
    'Retrospective',
    'Innovative',
    'Forward Thinking',
    'Scholar',
    'Exploration',
    'Creativity',
    'Inductive Reasoning',
    'Open-mindedness',
    'Extraspection',
    'Curiousity',
    'Information Processing',
    'Diverse',
  ],
  'Learn how to be responsible and accountable': [
    'High Standards',
    'Core Values',
    'Ethics',
    'Maintenance',
    'Moderation',
    'Risk Management',
    'Work Ethic',
    'Authentic',
    'Systematic',
    'Responsible',
    'Accountability',
    'Preservation',
    'Strong Will',
    'Meticulous',
    'Virtue',
    'Traditionalism',
    'Discipline',
    'Maturity',
    'Self-confidence',
    'Assertion',
    'External Awareness',
    'Prioritization',
    'Impervious',
  ],
  'Find a romantic partner': [
    'Socialization',
    'Amiability',
    'Social Network',
    'Interpersonal',
    'Self-awareness',
    'Emotional Intelligence',
    'Self-care',
    'Social Awareness',
    'Kindness',
    'Patience',
    'Respect',
    'Empathy',
    'Psychological',
    'Physical',
    'Romance',
    'Self-confidence',
    'Charisma',
    'Uniqueness',
    'Control of Desire',
    'Interesting',
    'Chivalry',
    'Gentleness',
    'Considerate',
    'Conversationalist',
    'Caring',
    'Entertaining',
    'Anxiety Control',
    'Good Natured',
    'Performance',
    'COmmunication',
    'Sexual',
    'Aggreable',
    'Passion',
    'Sympathetic',
    'Trust',
    'Comfort',
    'Honesty',
    'Authentic',
    'Proactive',
    'Lively',
    'Aesthetic',
    'Maintenance',
    'Presentation',
    'Intimacy',
  ],
  'Learn how to be systematic and plan': [
    'External Awareness',
    'Proactive',
    'Deductive Reasoning',
    'Extraspection',
    'Risk Management',
    'Systematic',
    'Responsible',
    'Thorough',
    'Meticulous',
    'Time Management',
    'Discipline',
    'Dedication',
    'Retrospective',
    'Analytical',
    'Abstract',
    'Planning',
    'Methodical',
    'Open-minded',
    'Flexible',
    'Prioritization',
    'Visionary',
  ],
  'Learn to be charismatic and have a good image': [
    'Emotion Control',
    'Socialization',
    'Amiambility',
    'Interpersonal',
    'Self-awareness',
    'Emotional Intelligence',
    'Self-care',
    'Social Awareness',
    'Mindfulness',
    'Empathy',
    'Psychology',
    'Physical',
    'Self-confidence',
    'Charisma',
    'Uniqueness',
    'Interesting',
    'Conversationalist',
    'Eloquent',
    'Entertaining',
    'Friendly',
    'Anxiety Control',
    'Good Natured',
    'Joy',
    'Communication',
    'Agreeable',
    'Sympathetic',
    'Enabler',
    'Humble',
    'Grounded',
    'Retrospective',
    'Thoughtful',
    'Methodical',
    'Change',
    'Mindfulness',
    'Mindset',
    'Visionary',
    'Society',
    'Optimism',
  ],
  'Help the environment': [
    'Core Values',
    'Ethics',
    'Reality',
    'Responsive',
    'Maintenance',
    'Acceptance',
    'Sciences',
    'Proactive',
    'Extraspective',
    'Purpose',
    'Preservation',
    'Inspiration',
    'Progress',
    'Problem Solving',
    'Harmonious',
    'Service',
    'Nature',
    'Dedication',
    'Humble',
    'Grounded',
    'Retrospective',
    'Thoughtful',
    'Methodical',
    'Change',
    'Mindfulness',
    'Mindset',
    'Visionary',
    'Society',
    'Optimism',
  ],
  'Revolutionize the world': [
    'Positive Influence',
    'Optimism',
    'Mentality',
    'Resilience',
    'Impervious',
    'Assertion',
    'Introspection',
    'Visionary',
    'Prioritization',
    'Society',
    'Humanitarian',
    'Fulfillment',
    'Change',
    'Planning',
    'Thoughtful',
    'Abstract',
    'Spontaneity',
    'Pragmaticism',
    'Uniqueness',
    'Morality',
    'Innovative',
    'Modernized',
    'Forward Thinking',
    'Dedication',
    'Discipline',
    'Service',
    'Execution',
    'Motivation',
    'Strong Will',
    'Pride',
    'Progress',
    'Inspiration',
    'Open-minded',
    'Purpose',
    'Impervious',
    'Core Values',
  ],
  'Accomplish a great feat': [
    'High Standards',
    ' Practice',
    ' Self-worth',
    ' Proactive',
    ' Impervious',
    'Memory',
    'Resourceful',
    'Work-ethic',
    'Authentic',
    'Courage',
    'Focus',
    'Pride',
    'Success',
    'Thorough',
    'Strong Will',
    'Growth',
    'Passion',
    'Motivation',
    'Meticulous',
    'Perseverence',
    'Time Management',
    'Execution',
    'Discipline',
    'Dedication',
    'Productive',
    'Performance',
    'Love of Challenge',
    'Innovative',
    'Thoughtful',
    'Mindset',
    'Prioritization',
    'Self-care',
    'Visionary',
    'Introspective',
    'Assertion',
    'Resilience',
    'Optimism',
  ],
  'Learn to be organized': [
    'Mentality',
    'Self-awareness',
    'Introspection',
    'Self-care',
    'Prioritization',
    'Mindfulness',
    'Methodical',
    'Self-control',
    'Thoughtful',
    'Patience',
    'Situational Awareness',
    'Grounded',
    'Dedication',
    'Discipline',
    'Meticulous',
    'Preservation',
    'Thorough',
    'Accountability',
    'Responsible',
    'Focus',
    'Systematic',
    'Work Ethic',
    'Risk Management',
    'Moderation',
    'Impervious',
    'Lifeskills',
    'External Awareness',
    'Maintenance',
    'Presentation',
    'Practifce',
    'Core Values',
    'High Standards',
  ],
};

let goals = prompt(
  'Using comma separated values, type up to five of the goals below you are seeking to learn \n' +
    '1. ' +
    goal_list[0] +
    '\n' +
    '2. ' +
    goal_list[1] +
    '\n' +
    '3. ' +
    goal_list[2] +
    '\n' +
    '4. ' +
    goal_list[3] +
    '\n' +
    '5. ' +
    goal_list[4] +
    '\n' +
    '6. ' +
    goal_list[5] +
    '\n' +
    '7. ' +
    goal_list[6] +
    '\n' +
    '8. ' +
    goal_list[7] +
    '\n' +
    '9. ' +
    goal_list[8] +
    '\n' +
    '10. ' +
    goal_list[9] +
    '\n' +
    '11. ' +
    goal_list[10] +
    '\n' +
    '12. ' +
    goal_list[11] +
    '\n' +
    '13. ' +
    goal_list[12] +
    '\n' +
    '14. ' +
    goal_list[14] +
    '\n' +
    '15. ' +
    goal_list[15] +
    '\n' +
    '16. ' +
    goal_list[15] +
    '\n' +
    '17. ' +
    goal_list[16] +
    '\n' +
    '18. ' +
    goal_list[17] +
    '\n' +
    '19. ' +
    goal_list[18] +
    '\n'
);

goals = goals.split(',');
const goals_int = [];

for (let i = 0; i < goals.length; i++) {
  goals_int.push(goal_list[parseInt(goals[i]) - 1]);
}

output.push(goals_int);

const lifestyles = {
  'Humble/minimalist': [
    'Ethics',
    'Reality',
    'Moderation',
    'Humble',
    'Appreciation',
    'Grounded',
    'Self-control',
    'Contentment',
  ],
  'Extravagent/luxury': [
    'Presentation',
    'Aesthetic',
    'Comfort',
    'Self Worth',
    'Dedication',
    'Business Knowledge',
    'Financial Literacy',
    'Prioritization',
    'Visionary',
    'Assertion',
  ],
  'Vagabond/travel': [
    'Spiritual',
    'Diverse',
    'Lively',
    'Curiosity',
    'Open-mindedness',
    'Exploration',
    'Appreciation',
    'Nature',
    'Grounded',
    'Spontaneity',
    'Change',
  ],
  'Standard/modest': [
    'Ethics',
    'Comfort',
    'Moderation',
    'Appreciation',
    'Traditionalism',
    'Financial Literacy',
    'Contentment',
  ],
};

let lifestyle = prompt(
  'Choose one of the following of the type of lifestyle you want to live \n' +
    '1. ' +
    lifestyles[0] +
    '\n' +
    '2. ' +
    lifestyles[1] +
    '\n' +
    '3. ' +
    lifestyles[2] +
    '\n' +
    '4. ' +
    lifestyles[3] +
    '\n'
);

lifestyle = parseInt(lifestyle);
output.push(lifestyles[lifestyle - 1]);

const focuses = {
  'Family focused/Relationships': [
    'Positive Influence',
    'Resilience',
    'Emotion Control',
    'Interpersonal',
    'Good Friend',
    'Emotional Intelligence',
    'Social Awareness',
    'Amiable Love',
    'Alturism',
    'Flexibility',
    'Kindness',
    'Forgiveness',
    'Planning',
    'Patience',
    'Situational Awareness',
    'Respect',
    'Empathy',
    'Psychology',
    'Romance',
    'Control of Desire',
    'Chivalry',
    'Gentleness',
    'Morality',
    'Considerate',
    'Caring',
    'Friendly',
    'Good Natured',
    'Financial Literacy',
    'Joy',
    'Peace',
    'Goodness',
    'Faithfulness',
    'Maturity',
    'Reasonable',
    'Grounded',
    'Communication',
    'Sexual',
    'Service',
    'Harmonious',
    'Agreeable',
    'Appreciation',
    'Leadership',
    'Mentorship',
    'Time Management',
    'Legacy',
    'Sympathetic',
    'Enabler',
    'Humble',
    'Inspiration',
    'Trust',
    'Preseration',
    'Loyalty',
    'Open-mindedness',
    'Generous',
    'Courage',
    'Work Ethic',
    'Provision',
    'Extraspection',
    'Risk Management',
    'Inductive Reasoning',
    'Rhetoric',
    'Moderation',
    'Urgency',
    'Responsive',
    'Presentation',
    'Intimacy',
  ],
  'Accomplishment focused': [
    'Optimism',
    'Resilience',
    'Assertion',
    'Introspection',
    'Visionary',
    'Self-care',
    'Society',
    'Methodical',
    'Self-control',
    'Planning',
    'Patience',
    'Abstract',
    'Pragmaticism',
    'Analytical',
    'Physical',
    'Retrospective',
    'Innovative',
    'Forward Thinking',
    'Independence',
    'Productive',
    'Problem Solving',
    'Time Management',
    'Meticulous',
    'Strong Will',
    'Thorough',
    'Legacy',
    'Creativity',
    'Deductive Reasoning',
    'Inspiration',
    'Focus',
    'Courage',
    'Systematic',
    'Work Ethic',
    'Inductive Reasoning',
    'Stoicism',
    'Curiosity',
    'Logic',
    'Impervious',
    'Science',
    'Responsive',
  ],
  'Pursuit of interests': [
    'Self-awareness',
    'Assertion',
    'Introspection',
    'Self-care',
    'Flexibility',
    'Mindfulness',
    'Self-control',
    'Spontaneity',
    'Psychology',
    'Retrospective',
    'Joy',
    'Independence',
    'Reasonable',
    'Harmonious',
    'Appreciation',
    'Exploration',
    'Creativity',
    'Preservation',
    'Focus',
    'Open-mindedness',
    'Courage',
    'Inductive Reasoning',
    'Stoicism',
    'Curiousity',
    'Moderation',
    'Impervious',
    'Diverse',
    'Responsive',
  ],
  'Scholar focused': [
    'Self-awareness',
    'Introspection',
    'Visionary',
    'Patience',
    'Abstract',
    'Pragmaticism',
    'Analytical',
    'Retrospective',
    'History',
    'Scholar',
    'Independence',
    'Grounded',
    'Problem Solving',
    'Mentorship',
    'Time Management',
    'Meticulous',
    'Strong Will',
    'Thorough',
    'Creativity',
    'Deductive Reasoning',
    'Focus',
    'Systematic',
    'Work Ethic',
    'Inductive Reasoning',
    'Stoicism',
    'Curiosity',
    'Logic',
    'Science',
    'How or Why',
  ],
  'Career focused': [
    'Resilience',
    'Emotion Control',
    'Social Network',
    'Self-awareness',
    'Assertion',
    'Self-care',
    'Flexibility',
    'Self-control',
    'Planning',
    'Patience',
    'Pragmaticism',
    'Analytical',
    'Empathy',
    'Psychology',
    'Charisma',
    'Retrospective',
    'Innovative',
    'Financial Literacy',
    'Forward Thinking',
    'Business Knowledge',
    'Matiruity',
    'Performance',
    'Reasonable',
    'Productive',
    'Communication',
    'Harmonious',
    'Problem Solving',
    'Appreciation',
    'Leadership',
    'Mentorship',
    'Time Management',
    'Meticulous',
    'Strong Will',
    'Thorough',
    'Creativity',
    'Enabler',
    'Humble',
    'Inspiration',
    'Trust',
    'Focus',
    'Open-mindedness',
    'Courage',
    'Systematic',
    'Work Ethic',
    'Extraspection',
    'Risk Management',
    'Inductive Reasoning',
    'Deductive Reasoning',
    'Stoicism',
    'Logic',
    'Rhetoric',
    'Moderation',
    'Responsive',
    'Presentation',
  ],
  'Faith focused': [
    'Positive Influence',
    'Interpersonal',
    'Self-awareness',
    'Introspection',
    'Good Friend',
    'Visonary',
    'Amiable Love',
    'Alturism',
    'Society',
    'Good Deed',
    'Humanitarian',
    'Mindfulness',
    'Kindness',
    'Self-control',
    'Abstract',
    'Analytical',
    'Empathy',
    'Gentleness',
    'Morality',
    'Considerate',
    'Caring',
    'Friendly',
    'Good Natured',
    'Joy',
    'Peace',
    'Faithfulness',
    'History',
    'Grounded',
    'Harmonious',
    'Agreeable',
    'Appreciation',
    'Mentorship',
    'Thorough',
    'Sympathetic',
    'Enabler',
    'Humble',
    'Inspiration',
    'Trust',
    'Loyalty',
    'Open-mindedness',
    'Generous',
    'Provision',
    'Risk Management',
    'Deductive Reasoning',
    'Curiousity',
    'Rhetoric',
    'Transcendant',
    'Moderation',
    'Urgency',
    'Divine/Righteous',
    'Responsive',
    'Spiritual',
  ],
  'Growth focused': [
    'Optimism',
    'Resilience',
    'Social Network',
    'Interpersonal',
    'Self-awareness',
    'Introspection',
    'Emotional Intelligence',
    'Self-care',
    'Humanitarian',
    'Flexibility',
    'Mindfulness',
    'Kindness',
    'Change',
    'Self-control',
    'Planning',
    'Pragmaticism',
    'Analytical',
    'Empathy',
    'Physical',
    'Morality',
    'Anxiety Control',
    'Retrospective',
    'Love of Challenge',
    'Financial Literacy',
    'Forward Thinking',
    'Goodness',
    'Maturity',
    'Performance',
    'Scholar',
    'Reasonable',
    'Grounded',
    'Productive',
    'Harmonious',
    'Problem Solving',
    'Mentorship',
    'Growth',
    'Strong Will',
    'Exploration',
    'Thorough',
    'Creativity',
    'Humble',
    'Preservation',
    'Focus',
    'Open-mindedness',
    'Courage',
    'Systematic',
    'Work Ethic',
    'Deductive Reasoning',
    'Inductive Reasoning',
    'Stoicism',
    'Curiosity',
    'Logic',
    'Rhetoric',
    'Moderation',
    'Impervious',
    'Diverse',
    'Responsive',
    'How or Why',
  ],
  'Self-expression focused': [
    'Emotion Control',
    'Socialization',
    'Interpersonal',
    'Self-awareness',
    'Assertion',
    'Good Friend',
    'Self-care',
    'Mindfulness',
    'Situational Awareness',
    'Respect',
    'Abstract',
    'Spontaneity',
    'Empathy',
    'Charisma',
    'Uniqueness',
    'Interesting',
    'Conversationalist',
    'Entertaining',
    'Eloquent',
    'Friendly',
    'Anxiety Control',
    'Joy',
    'Grounded',
    'Communication',
    'Agreeable',
    'Appreciation',
    'Exploration',
    'Creativity',
    'Humble',
    'Inspiration',
    'Trust',
    'Preservation',
    'Open-mindedness',
    'Courage',
    'Extraspection',
    'Curiosity',
    'Rhetoric',
    'Responsive',
    'Presentation',
  ],
  'Service focused': [
    'Positive Infleunce',
    'Socialization',
    'Amiability',
    'Interpersonal',
    'Good Friend',
    'Emotional Intelligence',
    'Social Awareness',
    'Amiable Love',
    'Alturism',
    'Society',
    'Good Deed',
    'Humanitarian',
    'Flexibility',
    'Kindness',
    'Forgiveness',
    'Respect',
    'Empathy',
    'Charisma',
    'Chivalry',
    'Gentleness',
    'Morality',
    'Considerate',
    'Caring',
    'Friendly',
    'Goodness',
    'Grounded',
    'Communication',
    'Service',
    'Harmonious',
    'Agreeable',
    'Problem Solving',
    'Appreciation',
    'Mentorship',
    'Time Management',
    'Strong Will',
    'Thorough',
    'Legacy',
    'Sympathetic',
    'Enabler',
    'Humble',
    'Inspiration',
    'Trust',
    'Open-mindedness',
    'Generous',
    'Courage',
    'Provision',
    'Extraspection',
    'Risk Management',
    'Inductive Reasoning',
    'Rhetoric',
    'Moderation',
    'Urgency',
    'Impervious',
    'Responsive',
  ],
  'Living to fullest focused': [
    'Optimism',
    'Socialization',
    'Self-awareness',
    'Introspection',
    'Visionary',
    'Self-care',
    'Flexibility',
    'Mindfulness',
    'Change',
    'Abstract',
    'Situational Awareness',
    'Spontaneity',
    'Friendly',
    'Anxiety Control',
    'Forward Thinking',
    'Joy',
    'Peace',
    'Goodness',
    'Performance',
    'Independence',
    'Grounded',
    'Productive',
    'Communication',
    'Harmonious',
    'Appreciation',
    'Mentorship',
    'Strong Will',
    'Exploration',
    'Thorough',
    'Legacy',
    'Creativity',
    'Enabler',
    'Inspiration',
    'Focus',
    'Open-mindedness',
    'Courage',
    'Work Ethic',
    'Extraspection',
    'Inductive Reasoning',
    'Curiosity',
    'Logic',
    'Transcendant',
    'Urgency',
    'Impervious',
    'Diverse',
  ],
};

let selectedFocus = prompt(
  'Choose one of the following of the type of focus you want to live \n' +
    '1. ' +
    focuses[0] +
    '\n' +
    '2. ' +
    focuses[1] +
    '\n' +
    '3. ' +
    focuses[2] +
    '\n' +
    '4. ' +
    focuses[3] +
    '\n' +
    '5. ' +
    focuses[4] +
    '\n' +
    '6. ' +
    focuses[5] +
    '\n' +
    '7. ' +
    focuses[6] +
    '\n' +
    '8. ' +
    focuses[7] +
    '\n' +
    '9. ' +
    focuses[8] +
    '\n' +
    '10. ' +
    focuses[9] +
    '\n'
);

selectedFocus = parseInt(selectedFocus);
output.push(focuses[selectedFocus - 1]);

const values_list = {
  Accountability: [
    'Accountability',
    'Resilience',
    'Assertion',
    'Social Awareness',
    'Prioritization',
    'Methodical',
    'Thoughtful',
    'Respect',
    'Pragmaticism',
    'Analytical',
    'Self-confidence',
    'Retrospective',
    'Reasonable',
    'Virtue',
    'Strong Will',
    'Thorough',
    'Pride',
    'Enabler',
    'Trust',
    'Responsible',
    'Courage',
    'Honesty',
    'Proactive',
    'Responsive',
    'Maintenance',
    'Core Values',
    'High Standards',
    'Preservation',
  ],
  Ambition: [
    'Passion',
    'Visionary',
    'Self-confidence',
    'Dedication',
    'Preservation',
    'Discipline',
    'Execution',
    'Perseverence',
    'Passion',
    'Pride',
    'Focus',
    'Purpose',
    'Work Ethic',
    'Practice',
    'High Standards',
  ],
  Authenticity: [
    'Self-awareness',
    'Assertion',
    'Self-care',
    'Prioritization',
    'Mindfulness',
    'Self-control',
    'Respect',
    'Self-confidence',
    'Uniqueness',
    'Faithfulness',
    'Independence',
    'Grounded',
    'Self-love',
    'Self Worth',
    'Comfort',
    'Understanding',
    'Authentic',
    'Introspection',
    'Impervious',
    'Acceptance',
    'Reality',
    'Core Values',
  ],
  Competition: [
    'Socialization',
    'Assertion',
    'Visionary',
    'Prioritization',
    'Self-control',
    'Self-confidence',
    'Innovative',
    'Love of Challenge',
    'Performance',
    'Execution',
    'Motivation',
    'Passion',
    'Strong Will',
    'Pride',
    'Success',
    'Creativity',
    'Inspiration',
    'Focus',
    'Work Ethic',
    'Proactive',
    'Self-worth',
    'Responsive',
    'Practice',
    'High Standards',
  ],
  Creativity: [
    'Introspection',
    'Visionary',
    'Mindset',
    'Change',
    'Thoughtful',
    'Abstract',
    'Spontaneity',
    'Uniqueness',
    'Innovative',
    'Exploration',
    'Deductive Reasoning',
    'Open-mindedness',
    'Flexible',
    'Extraspection',
    'Curiosity',
    'Resourceful',
    'Information Processing',
    'Diverse',
  ],
  Curiosity: [
    'Optimism',
    'Socialization',
    'Visionary',
    'Mindfulness',
    'Thoughtful',
    'Spontaneity',
    'Analytical',
    'Retrospective',
    'Forward Thinking',
    'Meticulous',
    'Exploration',
    'Growth',
    'Thorough',
    'Inductive Reasoning',
    'Understanding',
    'Extraspection',
    'Curiousity',
    'Learning',
    'Proactive',
    'Information Processing',
    'Diverse',
    'How and Why',
  ],
  Discipline: [
    'Mentality',
    'Resilience',
    'Emotion Control',
    'Self-awareness',
    'Assertion',
    'Self-care',
    'Prioritization',
    'Mindfulness',
    'Methodical',
    'Self-control',
    'Thoughtful',
    'Pragmaticism',
    'Anxiety Control',
    'Goodness',
    'Faithfulness',
    'Productive',
    'Dedication',
    'Discipline',
    'Execution',
    'Time Management',
    'Perseverence',
    'Meticulous',
    'Motivation',
    'Strong Will',
    'Thorough',
    'Pride',
    'Preservation',
    'Focus',
    'Work Ethic',
    'Stoicism',
    'Moderation',
    'Impervious',
    'Maintenance',
    'Practice',
    'High Standards',
  ],
  Diversity: [
    'Introspection',
    'Visionary',
    'Flexibility',
    'Contentment',
    'Change',
    'Mindfulness',
    'Thoughtful',
    'Spontaneity',
    'Uniqueness',
    'Good Natured',
    'Harmonious',
    'Exploration',
    'Creativity',
    'Deductive Reasoning',
    'Open-mindedness',
    'Extraspection',
    'Curiousity',
    'Diverse',
    'External Awareness',
  ],
  Education: [
    'Introspection',
    'Visionary',
    'Thoughtful',
    'Analytical',
    'Psychological',
    'Retrospective',
    'Love of Challenge',
    'Financial Literacy',
    'Business Knowledge',
    'Scholar',
    'Dedication',
    'Virtue',
    'Self Worth',
    'Growth',
    'Exploration',
    'Progress',
    'Understanding',
    'Open-mindedness',
    'Curiousity',
    'Learning',
    'Memory',
    'Information Processing',
    'Science',
    'How or Why',
  ],
  Efficiency: [
    'Self-awareness',
    'Visionary',
    'Prioritization',
    'Mindfulness',
    'Methodical',
    'Planning',
    'Thoughtful',
    'Pragmaticism',
    'Analytical',
    'Retrospective',
    'Performance',
    'Modernized',
    'Productive',
    'Dedication',
    'Problem Solving',
    'Execution',
    'Meticulous',
    'Thorough',
    'Success',
    'Focus',
    'Systematic',
    'Work Ethic',
    'Resourceful',
  ],
  Equality: [
    'Positive Influence',
    'Socialization',
    'Interpersonal',
    'Good Friend',
    'Amiable Love',
    'Humanitarian',
    'Good Deed',
    'Society',
    'Kindness',
    'Respect',
    'Empathy',
    'Gentleness',
    'Morality',
    'Caring',
    'Good Natured',
    'Goodness',
    'Service',
    'Harmonious',
    'Agreeable',
    'Sympathetic',
    'Enabler',
    'Humble',
    'Generous',
    'Provision',
    'Lively',
    'Acceptance',
  ],
  Ethics: [
    'Positive Influence',
    'External Awareness',
    'Society',
    'Methodical',
    'Thoughtful',
    'Respect',
    'Pragmaticism',
    'Morality',
    'Good Natured',
    'Forward Thinking',
    'Reasonable',
    'Traditionalism',
    'Virtue',
    'Trust',
    'Preservation',
    'Responsible',
    'Accountability',
    'Systematic',
    'Purpose',
    'Extraspection',
    'Risk Mangement',
    'Deductive Reasoning',
    'Logic',
    'Maintenance',
    'Core Values',
    'High Standards',
  ],
  Faith: [
    'Spiritual',
    'Acceptance',
    'Transcendant',
    'Trust',
    'Perseverence',
    'Discipline',
    'Failthfulness',
    'Self-control',
  ],
  Family: [
    'Positive Influence',
    'Optimism',
    'Resilience',
    'Emotion Control',
    'Interpersonal',
    'Self-awareness',
    'Emotional Intelligence',
    'Visionary',
    'Prioritization',
    'Alturism',
    'Mindset',
    'Kindness',
    'Forgiveness',
    'Self-control',
    'Patience',
    'Thoughtful',
    'Respect',
    'Empathy',
    'Considerate',
    'Caring',
    'Financial Literacy',
    'Dedication',
    'Communication',
    'Service',
    'Harmonious',
    'Problem Solving',
    'Appreciation',
    'Leadership',
    'Time Management',
    'Perseverence',
    'Passion',
    'Legacy',
    'Pride',
    'Synpathetic',
    'Grateful',
    'Enabler',
    'Humble',
    'Inspiration',
    'Trust',
    'Comfort',
    'Preservation',
    'Loytalty',
    'Understanding',
    'Responsible',
    'Generous',
    'Honesty',
    'Provision',
    'Proactive',
    'External Awareness',
    'Responsive',
    'Intimacy',
    'Mindfulness',
  ],
  Freedom: [
    'Core Values',
    'Responsive',
    'Maintenance',
    'Diverse',
    'Self-worth',
    'Lively',
    'Proactive',
    'Impervious',
    'Resourceful',
    'Work Ethic',
    'Purpose',
    'Open-mindedness',
    'Responsible',
    'Accountability',
    'Preservation',
    'Strong Will',
    'Perseverence',
    'Problem Solving',
    'Independence',
    'Peace',
    'Financial Literacy',
    'Uniqueness',
    'Self-confidence',
    'Physical',
    'Spontaneity',
    'Mindfulness',
    'Contentment',
    'Flexibility',
    'Mindset',
    'Prioritization',
    'Introspection',
    'Self-awareness',
    'Resilience',
    'Optimism',
  ],
  Friendship: [
    'Positive Influence',
    'Mentality',
    'Emotion Control',
    'Socialization',
    'Amiability',
    'Social Network',
    'Interpersonal',
    'Self-awareness',
    'Good Friend',
    'Emotional Intelligence',
    'Social Awareness',
    'Amiable Love',
    'Prioritization',
    'Alturism',
    'Good Deed',
    'Kindness',
    'Forgiveness',
    'Self-control',
    'Patience',
    'Thoughtful',
    'Respect',
    'Psychology',
    'Entertaining',
    'Caring',
    'Considerate',
    'Conversationalist',
    'Friendly',
    'Good Natured',
    'Goodness',
    'Dedication',
    'Communication',
    'Harmonious',
    'Agreeable',
    'Appreciation',
    'Sympathetic',
    'Grateful',
    'Enabler',
    'Humble',
    'Trust',
    'Comfort',
    'Preservation',
    'Loyalty',
    'Accountability',
    'Open-mindedness',
    'Generous',
    'Honesty',
    'Authentic',
    'Proactive',
    'Acceptance',
    'Responsive',
    'Presentation',
    'Intimacy',
    'High Standards',
    'Interesting',
  ],
  Fun: [
    'Aesthetic',
    'Diverse',
    'Information Processing',
    'Lively',
    'Impervious',
    'Curiousity',
    'Authentic',
    'Open-mindedness',
    'Happiness',
    'Creativity',
    'Grateful',
    'Performance',
    'Innovative',
    'Entertaining',
    'Conversationalist',
    'Control of Desire',
    'Uniqueness',
    'Mindfulness',
    'Contentment',
    'Mindfulness',
    'Flexibility',
    'Fulfillment',
    'Mindset',
    'Self-care',
    'Self-awareness',
    'Interesting',
  ],
  'Future-focused': [
    'Positive Influence',
    'Optimism',
    'Mentality',
    'Visionary',
    'Self-care',
    'Prioritization',
    'Mindfulness',
    'Planning',
    'Thoughtful',
    'Abstract',
    'Pragmaticism',
    'Analytical',
    'Innovative',
    'Forward Thinking',
    'Dedication',
    'Time Management',
    'Prioritization',
    'Legacy',
    'Preservation',
    'Accountability',
    'Responsible',
    'Focus',
    'Systematic',
    'Work Ethic',
    'Risk Management',
    'Inductive Reasoning',
    'Learning',
    'Moderation',
    'Maintenance',
    'Responsive',
  ],
  Generosity: [
    'Core Values',
    'Presentation',
    'External Awareness',
    'Proactive',
    'Provision',
    'Generous',
    'Humble',
    'Enabler',
    'Sympathetic',
    'Harmonious',
    'Service',
    'Grounded',
    'Goodness',
    'Friendly',
    'Good Natured',
    'Caring',
    'Considerate',
    'Gentleness',
    'Empathy',
    'Situational Awareness',
    'Respect',
    'Kindness',
    'Mindfulness',
    'Humanitarian',
    'Good Deed',
    'Society',
    'Alturism',
    'Amiable Love',
    'Social Awareness',
    'Emotional Intelligence',
    'Interpersonal',
    'Optimism',
    'Positive Influence',
  ],
  Grace: [
    'Optimism',
    'Mentality',
    'Resilience',
    ' Emotion Control',
    'Interpersonal',
    'Self-awareness',
    'Emotional Intelligence',
    'Social Awareness',
    'Amiable Love',
    'Mindfulness',
    'Kindness',
    'Forgiveness',
    'Self-control',
    'Patience',
    'Respect',
    'Empathy',
    'Psychology',
    'Gentleness',
    'Considerate',
    'Caring',
    'Good Natured',
    'Communication',
    'Harmonious',
    'Agreeable',
    'Sympathetic',
    'Preservation',
    'Understanding',
    'Generous',
    'Proactive',
    'Information Processing',
    'Acceptance',
    'Responsive',
    'Presentation',
  ],
  Health: [
    'High Standards',
    'Responsive',
    'Maintenance',
    'Survival',
    'Life Skills',
    'Proactive',
    'Moderation',
    'Risk Management',
    'Provision',
    'Work Ethic',
    'Responsible',
    'Preservation',
    'Meticulous',
    'Fitness and Health',
    'Nature',
    'Reasonable',
    'Performance',
    'Gentleness',
    'Self-control',
    'Physical',
    'Respect',
    'Thoughtful',
    'Self-care',
    'Self-awareness',
    'Optimism',
  ],
  Honesty: [
    'Mentality',
    'Self-awareness',
    'Interpersonal',
    'Good Deed',
    'Mindfulness',
    'Self-control',
    'Thoughtful',
    'Respect',
    'Considerate',
    'Good Natured',
    'Communication',
    'Virtue',
    'Sympathetic',
    'Humble',
    'Trust',
    'Preservation',
    'Accountability',
    'Honesty',
    'Authentic',
    'Reality',
    'Ethics',
    'Core Values',
    'High Standards',
  ],
  Humility: [
    'Core Values',
    'Presentation',
    'External Awareness',
    'Proactive',
    'Moderation',
    'Humble',
    'Grateful',
    'Virtue',
    'Harmonious',
    'Agreeable',
    'Grounded',
    'Considerate',
    'Empahty',
    'Respect',
    'Thoughtful',
    'Self-control',
    'Mindfulness',
    'Social Awareness',
    'Self-awareness',
  ],
  Independence: [
    'Mentality',
    'Resilience',
    'Self-awareness',
    'Assertion',
    'Introspection',
    'Self-care',
    'Prioritization',
    'Flexibility',
    ' Mindfulness',
    'Methodical',
    'Situational Awareness',
    'Pragmaticism',
    'Physical',
    'Self-confidence',
    'Retrospective',
    'Love of Challenge',
    'Forward Thinking',
    'Financial Literacy',
    'Performance',
    'Independence',
    'Grounded',
    'Discipline',
    'Problem Solving',
    'Fitness and Health',
    'Execution',
    'Time Management',
    'Persevere3nce',
    'Growth',
    'Pride',
    'Preservation',
    'Understanding',
    'Accountability',
    'Responsible',
    'Focus',
    'Open-mindedness',
    'Work Ethic',
    'Extraspection',
    'Risk Management',
    'Deductive Reasoning',
    'Inductive Reasoning',
    'Stoicism',
    'Curiousity',
    'Resourceful',
    'Learning',
    'Impervious',
    'Proactive',
    'Information Processing',
    'Self-worth',
    'Life Skills',
    'Survival',
    'External Awareness',
    'Maintenance',
    'Responsive',
    'Reality',
    'Core Values',
  ],
  Integrity: [
    'High Standards',
    'Core Values',
    'Ethics',
    'Presentation',
    'Responsive',
    'Maintenance',
    'Proactive',
    'Impervious',
    'Work Ethic',
    'Purpose',
    'Authentic',
    'Honesty',
    'Responsible',
    'Accountability',
    'Understanding',
    'Self Worth',
    'Virtue',
    'Reasonable',
    'Goodness',
    'Good Natured',
    'Morality',
    'Respect',
    'Thoughtful',
    'Self-control',
    'Methodical',
    'Mindfulness',
    'Prioritization',
    'Good Friend',
    'Self-awareness',
    'Mentality',
  ],
  Leadership: ['All'],
  Love: [
    'Amiability',
    'Interpersonal',
    'Amiable Love',
    'Prioritization',
    'Good Deed',
    'Flexibility',
    'Kindness',
    'Forgiveness',
    'Patience',
    'Thoughtful',
    'Empathy',
    'Caring',
    'Communication',
    'Service',
    'Appreciation',
    'Sympathetic',
    'Grateful',
    'Humble',
    'Comfort',
    'Preservation',
    'Trust',
    'Loyalty',
    'Generous',
    'Provision',
    'Proactive',
    'External Awareness',
    'Presentation',
    'Intimacy',
    'Mindfulness',
  ],
  Loyalty: [
    'Core Values',
    'Maintenance',
    'Proactive',
    'Impervious',
    'Focus',
    'Preservation',
    'Loyalty',
    'Trust',
    'Pride',
    'Strong Will',
    'Virtue',
    'Service',
    'Dedication',
    'Faithfulness',
    'Respect',
    'Thoughtful',
    'Mindfulness',
    'Mindset',
    'Resilience',
  ],
  Optimism: [
    'Optimism',
    'Mentality',
    'Resilience',
    'Emotion Control',
    'Self-awareness',
    'Emotional Intelligence',
    'Visionary',
    'Social Awareness',
    'Good Deed',
    'Mindfulness',
    'Patience',
    'Thoughtful',
    'Situational Awareness',
    'Pragmaticism',
    'Psychology',
    'Charisma',
    'Good Natured',
    'Innovative',
    'Love of Challenge',
    'Forward Thinking',
    'Faithfulness',
    'Grounded',
    'Agreeable',
    'Appreciation',
    'Leadership',
    'Perseverence',
    'Growth',
    'Exploration',
    'Progress',
    'Inspiration',
    'Trust',
    'Understanding',
    'Learning',
    'Transcendant',
    'Impervious',
    'Proactive',
    'Information Processing',
  ],
  Nature: [
    'Spiritual',
    'Reality',
    'Aesthetic',
    'Survival',
    'External Awareness',
    'Transcendant',
    'Resourceful',
    'Curiosity',
    'Happiness',
    'Preservation',
    'Comfort',
    'Exploration',
    'Appreciation',
    'Nature',
    'Grounded',
    'Respect',
    'Contentment',
    'Mindfulness',
    'Fulfillment',
  ],
  Patriotism: [
    'Positive Influence',
    'Mentality',
    'Assertion',
    'Visionary',
    'Social Awareness',
    'Society',
    'Humanitarian',
    'Mindfulness',
    'Planning',
    'Thoughtful',
    'Situational Awareness',
    'Analytical',
    'Empahty',
    'Considerate',
    'Good Natured',
    'Modernized',
    'Peace',
    'Goodness',
    'Faithfulness',
    'History',
    'Dedication',
    'Service',
    'Harmonious',
    'Problem Solving',
    'Traditionalism',
    'Virtue',
    'Execution',
    'Perseverence',
    'Passion',
    'Legacy',
    'Pride',
    'Success',
    'Enabler',
    'Inspiration',
    'Preservation',
    'Loyalty',
    'Accountability',
    'Responsible',
    'Open-mindedness',
    'Generous',
    'Courage',
    'Systematic',
    'Honesty',
    'Purpose',
    'Provision',
    'Extraspection',
    'Risk Management',
    'Resourceful',
    'Moderation',
    'Impervious',
    'Proactive',
    'External Awareness',
    'Maintenance',
    'Acceptance',
    'Responsive',
    'Core Values',
  ],
  Patience: [
    'Core Values',
    'Ethics',
    'Practice',
    'Responsive',
    'Acceptance',
    'External Awareness',
    'Life Skills',
    'Information Processing',
    'Proactive',
    'Impervious',
    'Moderation',
    'Stoicism',
    'Extraspection',
    'Open-mindedness',
    'Understanding',
    'Preservation',
    'Humble',
    'Perseverence',
    'Virtue',
    'Agreeable',
    'Harmonious',
    'Communication',
    'Discipline',
    'Grounded',
    'Reasonable',
    'Maturity',
    'Peace',
    'Good Natured',
    'Friendly',
    'Conversationalist',
    'Considerate',
    'Gentleness',
    'Respect',
    'Situational Awareness',
    'Thoughtful',
    'Patience',
    'Self-control',
    'Mindfulness',
    'Mindset',
    'Amiable Love',
    'Social Awareness',
    'Emotional Intelligence',
    'Self-awareness',
    'Interpersonal',
  ],
  Perseverence: [
    'Optimism',
    'Mentality',
    'Resilience',
    'Emotion Control',
    'Self-awareness',
    'Mindfulness',
    'Methodical',
    'Self-control',
    'Planning',
    'Patience',
    'Thoughtful',
    'Situational Awareness',
    'Pragmaticism',
    'Psychology',
    'Self-confidence',
    'Anxiety Control',
    'Forward Thinking',
    'Grounded',
    'Productive',
    'Dedication',
    'Discipline',
    'Execution',
    'Time Management',
    'Self Worth',
    'Perseverence',
    'Motivation',
    'Strong Will',
    'Loyalty',
    'Accountability',
    'Responsible',
    'Focus',
    'Purpose',
    'Resourceful',
    'Impervious',
    'Proactive',
    'Responsive',
  ],
  Power: [
    'High Standards',
    'Core Values',
    'Presentation',
    'Responsive',
    'Maintenance',
    'External Awareness',
    'Self-worth',
    'Proactive',
    'Impervious',
    'Moderation',
    'Resourceful',
    'Stoicism',
    'Inductive Reasoning',
    'Risk Management',
    'Extraspection',
    'Work Ethic',
    'Systematic',
    'Courage',
    'Open-mindedness',
    'Focus',
    'Accountability',
    'Preservation',
    'Deductive Reasoning',
    'Creative',
    'Success',
    'Pride',
    'Strong Will',
    'Passion',
    'Meticulous',
    'Perseverence',
    'Time Management',
    'Leadership',
    'Execution',
    'Communication',
    'Discipline',
    'Independence',
    'Forward Thinking',
    'Love of Challenge',
    'Innovative',
    'Retrospective',
    'Anxiety Control',
    'Eloquent',
    'Entertaining',
    'Interesting',
    'Uniqueness',
    'Self-confidence',
    'Psychology',
    'Thoughtful',
    'Patience',
    'Planning',
    'Self-control',
    'Methodical',
    'Mindset',
    'Prioritization',
    'Social Awareness',
    'Self-care',
    'Visionary',
    'Emotional Intelligence',
    'Introspection',
    'Assertion',
    'Self-awareness',
    'Social Network',
    'Amiability',
    'Socialization',
    'Emotion Control',
    'Resilience',
    'Mentality',
  ],
  Pride: [
    'Mentality',
    'Resilience',
    'Emotion Control',
    'Self-awareness',
    'Assertion',
    'Introspection',
    'Self-care',
    'Prioritization',
    'Self-control',
    'Thoughtful',
    'Respect',
    'Self-confidence',
    'Charisma',
    'Anxiety Control',
    'Love of Challenge',
    'Independence',
    'Dedication',
    'Self-love',
    'Execution',
    'Self Worth',
    'Passion',
    'Strong Will',
    'Pride',
    'Legacy',
    'Success',
    'Courage',
    'Aesthetic',
    'Presentation',
    'High Standards',
  ],
  Reliability: [
    'High Standards',
    'Core Values',
    'Practice',
    'Maintenance',
    'External Awareness',
    'Self-worth',
    'Proactive',
    'Risk Management',
    'Extraspection',
    'Work Ethic',
    'Systematic',
    'Focus',
    'Responsible',
    'Accountability',
    'Understanding',
    'Preservation',
    'Inductive Reasoning',
    'Thorough',
    'Meticulous',
    'Perseverence',
    'Time Management',
    'Execution',
    'Discipline',
    'Dedication',
    'Performance',
    'Analytical',
    'Thoughtful',
    'Planning',
    'Methodical',
    'Mindfulness',
    'Mindset',
    'Prioritization',
    'Self-awareness',
    'Resilience',
  ],
  'Self-expression': [
    'Mentality',
    'Emotion Control',
    'Socialization',
    'Self-awareness',
    'Assertion',
    'Self-care',
    'Prioritization',
    'Fulfillment',
    'Thoughtful',
    'Self-confidence',
    'Uniqueness',
    'Interesting',
    'Emotional Intelligence',
    'Charisma',
    'Interesting',
    'Eloquent',
    'Independence',
    'Self-love',
    'Communication',
    'Self Worth',
    'Preservation',
    'Happiness',
    'Understanding',
    'Courage',
    'Authentic',
    'Lively',
    'Aesthetic',
    'Maintenance',
    'Presentation',
  ],
  Success: [
    'High Standards',
    'Practice',
    'External Awareness',
    'Proactive',
    'Impervious',
    'Resourceful',
    'Learning',
    'Inductive Reasoning',
    'Deductive Reasoning',
    'Risk Management',
    'Extraspection',
    'Work Ethic',
    'Systematic',
    'Open-mindedness',
    'Focus',
    'Responsible',
    'Accountability',
    'Understanding',
    'Loyalty',
    'Preservation',
    'Humble',
    'Creativity',
    'Success',
    'Thorough',
    'Strong Will',
    'Perseverence',
    'Time Management',
    'Execution',
    'Discipline',
    'Dedication',
    'Independence',
    'Performance',
    'Financial Literacy',
    'Forward Thinking',
    'Love of Challenge',
    'Innovative',
    'Anxiety Control',
    'Uniqueness',
    'Charisma',
    'Self-confidence',
    'Analytical',
    'Thoughtful',
    'Patience',
    'Planning',
    'Self-control',
    'Methodical',
    'Mindfulness',
    'Prioritization',
    'Visionary',
    'Self-care',
    'Introspection',
    'Assertion',
    'Self-awareness',
    'Interpersonal',
    'Emotion Control',
    'Resilience',
    'Optimism',
    'Mentality',
    'Positive Influence',
  ],
  Tradition: [
    'Mentality',
    'Resilience',
    'Prioritization',
    'Society',
    'Mindfulness',
    'Self-control',
    'Methodical',
    'Thoughtful',
    'Situational Awareness',
    'Respect',
    'Peace',
    'History',
    'Grounded',
    'Dedication',
    'Traditionalism',
    'Virtue',
    'Legacy',
    'Trust',
    'Preservation',
    'Loyalty',
    'Acountability',
    'Systematic',
    'Risk Management',
    'Moderation',
    'Impervious',
    'Maintenance',
    'Core Values',
  ],
  Change: [
    'Responsive',
    'External Awareness',
    'Diverse',
    'Proactive',
    'Resourceful',
    'Curiousity',
    'Deductive Reasoning',
    'Inductive Reasoning',
    'Extraspection',
    'Systematic',
    'Courage',
    'Open-mindedness',
    'Progress',
    'Legacy',
    'Exploration',
    'Growth',
    'Execution',
    'Dedication',
    'Innovative',
    'Retrospective',
    'Spontaneity',
    'Thoughtful',
    'Planning',
    'Methodical',
    'Change',
    'Mindfulness',
    'Flexibility',
    'Society',
    'Mindset',
    'Prioritization',
    'Assertion',
    'Positive Influence',
    'Resilience',
  ],
  Truth: [
    'Positive Influence',
    'Mentality',
    'Interpersonal',
    'Emotional Intelligence',
    'Mindset',
    'Good Deed',
    'Mindfulness',
    'Kindness',
    'Self-control',
    'Thoughtful',
    'Respect',
    'Analytical',
    'Retrospective',
    'Introspective',
    'Grounded',
    'Dedicated',
    'Agreeable',
    'Virtue',
    'Exploration',
    'Thorough',
    'Understanding',
    'Open-mindedness',
    'Impervious',
    'Courage',
    'Honesty',
    'Learning',
    'Proactive',
    'Information Processing',
    'How or Why',
    'Core Values',
  ],
  Trust: [
    'Moderation',
    'Risk Management',
    'Understanding',
    'Loyalty',
    'Trust',
    'Humble',
    'Grateful',
    'Strong Will',
    'Perseverence',
    'Appreciation',
    'Dedication',
    'Grounded',
    'Faithfulness',
    'Anxiety Control',
    'Self-confidence',
    'Thoughtful',
    'Patience',
    'Self-control',
    'Contentment',
    'Mindset',
    'Visionary',
    'Resilience',
    'Optimism',
  ],
};

let selectedValues = prompt(
  'Using comma separated values, type up to five of the values below you value \n' +
    '1. ' +
    values_list[0] +
    '\n' +
    '2. ' +
    values_list[1] +
    '\n' +
    '3. ' +
    values_list[2] +
    '\n' +
    '4. ' +
    values_list[3] +
    '\n' +
    '5. ' +
    values_list[4] +
    '\n' +
    '6. ' +
    values_list[5] +
    '\n' +
    '7. ' +
    values_list[6] +
    '\n' +
    '8. ' +
    values_list[7] +
    '\n' +
    '9. ' +
    values_list[8] +
    '\n' +
    '10. ' +
    values_list[9] +
    '\n' +
    '11. ' +
    values_list[10] +
    '\n' +
    '12. ' +
    values_list[11] +
    '\n' +
    '13. ' +
    values_list[12] +
    '\n' +
    '14. ' +
    values_list[14] +
    '\n' +
    '15. ' +
    values_list[15] +
    '\n' +
    '16. ' +
    values_list[15] +
    '\n' +
    '17. ' +
    values_list[16] +
    '\n' +
    '18. ' +
    values_list[17] +
    '\n' +
    '19. ' +
    values_list[18] +
    '\n' +
    '20. ' +
    values_list[19] +
    '\n' +
    '21. ' +
    values_list[20] +
    '\n' +
    '22. ' +
    values_list[21] +
    '\n' +
    '23. ' +
    values_list[22] +
    '\n' +
    '24. ' +
    values_list[23] +
    '\n' +
    '25. ' +
    values_list[24] +
    '\n' +
    '26. ' +
    values_list[25] +
    '\n' +
    '27. ' +
    values_list[26] +
    '\n' +
    '28. ' +
    values_list[27] +
    '\n' +
    '29. ' +
    values_list[28] +
    '\n' +
    '30. ' +
    values_list[29] +
    '\n' +
    '31. ' +
    values_list[30] +
    '\n' +
    '32. ' +
    values_list[31] +
    '\n' +
    '33. ' +
    values_list[32] +
    '\n' +
    '34. ' +
    values_list[33] +
    '\n' +
    '35. ' +
    values_list[34] +
    '\n' +
    '36. ' +
    values_list[35] +
    '\n' +
    '37. ' +
    values_list[36] +
    '\n' +
    '38. ' +
    values_list[37] +
    '\n' +
    '39. ' +
    values_list[38] +
    '\n' +
    '40. ' +
    values_list[39] +
    '\n' +
    '41. ' +
    values_list[40] +
    '\n' +
    '42. ' +
    values_list[41] +
    '\n' +
    '43. ' +
    values_list[42] +
    '\n' +
    '44. ' +
    values_list[43] +
    '\n' +
    '45. ' +
    values_list[44] +
    '\n'
);

selectedValues = selectedValues.split(',');
const values_int = [];

for (let i = 0; i < selectedValues.length; i++) {
  values_int.push(values_list[parseInt(selectedValues[i]) - 1]);
}

output.push(values_int);

console.log(output);

export { output };
