const values_list = new Map();
values_list.set("Accountability", [
    "Accountability",
    "Resilience",
    "Assertion",
    "Social Awareness",
    "Prioritization",
    "Methodical",
    "Thoughtful",
    "Respect",
    "Pragmaticism",
    "Analytical",
    "Self-confidence",
    "Retrospective",
    "Reasonable",
    "Virtue",
    "Strong Will",
    "Thorough",
    "Pride",
    "Enabler",
    "Trust",
    "Responsible",
    "Courage",
    "Honesty",
    "Proactive",
    "Responsive",
    "Maintenance",
    "Core Values",
    "High Standards",
    "Preservation"
]);

values_list.set("Ambition", [
    "Passion",
    "Visionary",
    "Self-confidence",
    "Dedication",
    "Preservation",
    "Discipline",
    "Execution",
    "Perseverence",
    "Passion",
    "Pride",
    "Focus",
    "Purpose",
    "Work Ethic",
    "Practice",
    "High Standards"
]);

values_list.set("Authenticity", [
    "Self-awareness",
    "Assertion",
    "Self-care",
    "Prioritization",
    "Mindfulness",
    "Self-control",
    "Respect",
    "Self-confidence",
    "Uniqueness",
    "Faithfulness",
    "Independence",
    "Grounded",
    "Self-love",
    "Self Worth",
    "Comfort",
    "Understanding",
    "Authentic",
    "Introspection",
    "Impervious",
    "Acceptance",
    "Reality",
    "Core Values"
]);

values_list.set("Competition", [
    "Socialization",
    "Assertion",
    "Visionary",
    "Prioritization",
    "Self-control",
    "Self-confidence",
    "Innovative",
    "Love of Challenge",
    "Performance",
    "Execution",
    "Motivation",
    "Passion",
    "Strong Will",
    "Pride",
    "Success",
    "Creativity",
    "Inspiration",
    "Focus",
    "Work Ethic",
    "Proactive",
    "Self-worth",
    "Responsive",
    "Practice",
    "High Standards"
]);

values_list.set("Creativity", [
    "Introspection",
    "Visionary",
    "Mindset",
    "Change",
    "Thoughtful",
    "Abstract",
    "Spontaneity",
    "Uniqueness",
    "Innovative",
    "Exploration",
    "Deductive Reasoning",
    "Open-mindedness",
    "Flexible",
    "Extraspection",
    "Curiosity",
    "Resourceful",
    "Information Processing",
    "Diverse"
]);

values_list.set("Curiosity", [
    "Optimism",
    "Socialization",
    "Visionary",
    "Mindfulness",
    "Thoughtful",
    "Spontaneity",
    "Analytical",
    "Retrospective",
    "Forward Thinking",
    "Meticulous",
    "Exploration",
    "Growth",
    "Thorough",
    "Inductive Reasoning",
    "Understanding",
    "Extraspection",
    "Curiousity",
    "Learning",
    "Proactive",
    "Information Processing",
    "Diverse",
    "How and Why"
]);

values_list.set("Discipline", [
    "Mentality",
    "Resilience",
    "Emotion Control",
    "Self-awareness",
    "Assertion",
    "Self-care",
    "Prioritization",
    "Mindfulness",
    "Methodical",
    "Self-control",
    "Thoughtful",
    "Pragmaticism",
    "Anxiety Control",
    "Goodness",
    "Faithfulness",
    "Productive",
    "Dedication",
    "Discipline",
    "Execution",
    "Time Management",
    "Perseverence",
    "Meticulous",
    "Motivation",
    "Strong Will",
    "Thorough",
    "Pride",
    "Preservation",
    "Focus",
    "Work Ethic",
    "Stoicism",
    "Moderation",
    "Impervious",
    "Maintenance",
    "Practice",
    "High Standards"
]);

values_list.set("Diversity", [
    "Introspection",
    "Visionary",
    "Flexibility",
    "Contentment",
    "Change",
    "Mindfulness",
    "Thoughtful",
    "Spontaneity",
    "Uniqueness",
    "Good Natured",
    "Harmonious",
    "Exploration",
    "Creativity",
    "Deductive Reasoning",
    "Open-mindedness",
    "Extraspection",
    "Curiousity",
    "Diverse",
    "External Awareness"
]);

values_list.set("Education", [
    "Introspection",
    "Visionary",
    "Thoughtful",
    "Analytical",
    "Psychological",
    "Retrospective",
    "Love of Challenge",
    "Financial Literacy",
    "Business Knowledge",
    "Scholar",
    "Dedication",
    "Virtue",
    "Self Worth",
    "Growth",
    "Exploration",
    "Progress",
    "Understanding",
    "Open-mindedness",
    "Curiousity",
    "Learning",
    "Memory",
    "Information Processing",
    "Science",
    "How or Why"
]);

values_list.set("Efficiency", [
    "Self-awareness",
    "Visionary",
    "Prioritization",
    "Mindfulness",
    "Methodical",
    "Planning",
    "Thoughtful",
    "Pragmaticism",
    "Analytical",
    "Retrospective",
    "Performance",
    "Modernized",
    "Productive",
    "Dedication",
    "Problem Solving",
    "Execution",
    "Meticulous",
    "Thorough",
    "Success",
    "Focus",
    "Systematic",
    "Work Ethic",
    "Resourceful"
]);

values_list.set("Equality", [
    "Positive Influence",
    "Socialization",
    "Interpersonal",
    "Good Friend",
    "Amiable Love",
    "Humanitarian",
    "Good Deed",
    "Society",
    "Kindness",
    "Respect",
    "Empathy",
    "Gentleness",
    "Morality",
    "Caring",
    "Good Natured",
    "Goodness",
    "Service",
    "Harmonious",
    "Agreeable",
    "Sympathetic",
    "Enabler",
    "Humble",
    "Generous",
    "Provision",
    "Lively",
    "Acceptance"
]);

values_list.set("Ethics", [
    "Positive Influence",
    "External Awareness",
    "Society",
    "Methodical",
    "Thoughtful",
    "Respect",
    "Pragmaticism",
    "Morality",
    "Good Natured",
    "Forward Thinking",
    "Reasonable",
    "Traditionalism",
    "Virtue",
    "Trust",
    "Preservation",
    "Responsible",
    "Accountability",
    "Systematic",
    "Purpose",
    "Extraspection",
    "Risk Mangement",
    "Deductive Reasoning",
    "Logic",
    "Maintenance",
    "Core Values",
    "High Standards"
]);

values_list.set("Faith", [
    "Spiritual",
    "Acceptance",
    "Transcendant",
    "Trust",
    "Perseverence",
    "Discipline",
    "Failthfulness",
    "Self-control"
]);

values_list.set("Family", [
    "Positive Influence",
    "Optimism",
    "Resilience",
    "Emotion Control",
    "Interpersonal",
    "Self-awareness",
    "Emotional Intelligence",
    "Visionary",
    "Prioritization",
    "Alturism",
    "Mindset",
    "Kindness",
    "Forgiveness",
    "Self-control",
    "Patience",
    "Thoughtful",
    "Respect",
    "Empathy",
    "Considerate",
    "Caring",
    "Financial Literacy",
    "Dedication",
    "Communication",
    "Service",
    "Harmonious",
    "Problem Solving",
    "Appreciation",
    "Leadership",
    "Time Management",
    "Perseverence",
    "Passion",
    "Legacy",
    "Pride",
    "Synpathetic",
    "Grateful",
    "Enabler",
    "Humble",
    "Inspiration",
    "Trust",
    "Comfort",
    "Preservation",
    "Loytalty",
    "Understanding",
    "Responsible",
    "Generous",
    "Honesty",
    "Provision",
    "Proactive",
    "External Awareness",
    "Responsive",
    "Intimacy",
    "Mindfulness"
]);

values_list.set("Freedom", [
    "Core Values",
    "Responsive",
    "Maintenance",
    "Diverse",
    "Self-worth",
    "Lively",
    "Proactive",
    "Impervious",
    "Resourceful",
    "Work Ethic",
    "Purpose",
    "Open-mindedness",
    "Responsible",
    "Accountability",
    "Preservation",
    "Strong Will",
    "Perseverence",
    "Problem Solving",
    "Independence",
    "Peace",
    "Financial Literacy",
    "Uniqueness",
    "Self-confidence",
    "Physical",
    "Spontaneity",
    "Mindfulness",
    "Contentment",
    "Flexibility",
    "Mindset",
    "Prioritization",
    "Introspection",
    "Self-awareness",
    "Resilience",
    "Optimism"
]);

values_list.set("Friendship", [
    "Positive Influence",
    "Mentality",
    "Emotion Control",
    "Socialization",
    "Amiability",
    "Social Network",
    "Interpersonal",
    "Self-awareness",
    "Good Friend",
    "Emotional Intelligence",
    "Social Awareness",
    "Amiable Love",
    "Prioritization",
    "Alturism",
    "Good Deed",
    "Kindness",
    "Forgiveness",
    "Self-control",
    "Patience",
    "Thoughtful",
    "Respect",
    "Psychology",
    "Entertaining",
    "Caring",
    "Considerate",
    "Conversationalist",
    "Friendly",
    "Good Natured",
    "Goodness",
    "Dedication",
    "Communication",
    "Harmonious",
    "Agreeable",
    "Appreciation",
    "Sympathetic",
    "Grateful",
    "Enabler",
    "Humble",
    "Trust",
    "Comfort",
    "Preservation",
    "Loyalty",
    "Accountability",
    "Open-mindedness",
    "Generous",
    "Honesty",
    "Authentic",
    "Proactive",
    "Acceptance",
    "Responsive",
    "Presentation",
    "Intimacy",
    "High Standards",
    "Interesting"
]);

values_list.set("Fun", [
    "Aesthetic",
    "Diverse",
    "Information Processing",
    "Lively",
    "Impervious",
    "Curiousity",
    "Authentic",
    "Open-mindedness",
    "Happiness",
    "Creativity",
    "Grateful",
    "Performance",
    "Innovative",
    "Entertaining",
    "Conversationalist",
    "Control of Desire",
    "Uniqueness",
    "Mindfulness",
    "Contentment",
    "Mindfulness",
    "Flexibility",
    "Fulfillment",
    "Mindset",
    "Self-care",
    "Self-awareness",
    "Interesting"
]);

values_list.set("Future-focused", [
    "Positive Influence",
    "Optimism",
    "Mentality",
    "Visionary",
    "Self-care",
    "Prioritization",
    "Mindfulness",
    "Planning",
    "Thoughtful",
    "Abstract",
    "Pragmaticism",
    "Analytical",
    "Innovative",
    "Forward Thinking",
    "Dedication",
    "Time Management",
    "Prioritization",
    "Legacy",
    "Preservation",
    "Accountability",
    "Responsible",
    "Focus",
    "Systematic",
    "Work Ethic",
    "Risk Management",
    "Inductive Reasoning",
    "Learning",
    "Moderation",
    "Maintenance",
    "Responsive"
]);

values_list.set("Generosity", [
    "Core Values",
    "Presentation",
    "External Awareness",
    "Proactive",
    "Provision",
    "Generous",
    "Humble",
    "Enabler",
    "Sympathetic",
    "Harmonious",
    "Service",
    "Grounded",
    "Goodness",
    "Friendly",
    "Good Natured",
    "Caring",
    "Considerate",
    "Gentleness",
    "Empathy",
    "Situational Awareness",
    "Respect",
    "Kindness",
    "Mindfulness",
    "Humanitarian",
    "Good Deed",
    "Society",
    "Alturism",
    "Amiable Love",
    "Social Awareness",
    "Emotional Intelligence",
    "Interpersonal",
    "Optimism",
    "Positive Influence"
]);

values_list.set("Grace", [
    "Optimism",
    "Mentality",
    "Resilience",
    " Emotion Control",
    "Interpersonal",
    "Self-awareness",
    "Emotional Intelligence",
    "Social Awareness",
    "Amiable Love",
    "Mindfulness",
    "Kindness",
    "Forgiveness",
    "Self-control",
    "Patience",
    "Respect",
    "Empathy",
    "Psychology",
    "Gentleness",
    "Considerate",
    "Caring",
    "Good Natured",
    "Communication",
    "Harmonious",
    "Agreeable",
    "Sympathetic",
    "Preservation",
    "Understanding",
    "Generous",
    "Proactive",
    "Information Processing",
    "Acceptance",
    "Responsive",
    "Presentation"
]);

values_list.set("Health", [
    "High Standards",
    "Responsive",
    "Maintenance",
    "Survival",
    "Life Skills",
    "Proactive",
    "Moderation",
    "Risk Management",
    "Provision",
    "Work Ethic",
    "Responsible",
    "Preservation",
    "Meticulous",
    "Fitness and Health",
    "Nature",
    "Reasonable",
    "Performance",
    "Gentleness",
    "Self-control",
    "Physical",
    "Respect",
    "Thoughtful",
    "Self-care",
    "Self-awareness",
    "Optimism"
]);

values_list.set("Honesty", [
    "Mentality",
    "Self-awareness",
    "Interpersonal",
    "Good Deed",
    "Mindfulness",
    "Self-control",
    "Thoughtful",
    "Respect",
    "Considerate",
    "Good Natured",
    "Communication",
    "Virtue",
    "Sympathetic",
    "Humble",
    "Trust",
    "Preservation",
    "Accountability",
    "Honesty",
    "Authentic",
    "Reality",
    "Ethics",
    "Core Values",
    "High Standards"
]);

values_list.set("Humility", [
    "Core Values",
    "Presentation",
    "External Awareness",
    "Proactive",
    "Moderation",
    "Humble",
    "Grateful",
    "Virtue",
    "Harmonious",
    "Agreeable",
    "Grounded",
    "Considerate",
    "Empahty",
    "Respect",
    "Thoughtful",
    "Self-control",
    "Mindfulness",
    "Social Awareness",
    "Self-awareness",
]);

values_list.set("Independence", [
    "Mentality",
    "Resilience",
    "Self-awareness",
    "Assertion",
    "Introspection",
    "Self-care",
    "Prioritization",
    "Flexibility",
    " Mindfulness",
    "Methodical",
    "Situational Awareness",
    "Pragmaticism",
    "Physical",
    "Self-confidence",
    "Retrospective",
    "Love of Challenge",
    "Forward Thinking",
    "Financial Literacy",
    "Performance",
    "Independence",
    "Grounded",
    "Discipline",
    "Problem Solving",
    "Fitness and Health",
    "Execution",
    "Time Management",
    "Persevere3nce",
    "Growth",
    "Pride",
    "Preservation",
    "Understanding",
    "Accountability",
    "Responsible",
    "Focus",
    "Open-mindedness",
    "Work Ethic",
    "Extraspection",
    "Risk Management",
    "Deductive Reasoning",
    "Inductive Reasoning",
    "Stoicism",
    "Curiousity",
    "Resourceful",
    "Learning",
    "Impervious",
    "Proactive",
    "Information Processing",
    "Self-worth",
    "Life Skills",
    "Survival",
    "External Awareness",
    "Maintenance",
    "Responsive",
    "Reality",
    "Core Values"
]);

values_list.set("Integrity", [
    "High Standards",
    "Core Values",
    "Ethics",
    "Presentation",
    "Responsive",
    "Maintenance",
    "Proactive",
    "Impervious",
    "Work Ethic",
    "Purpose",
    "Authentic",
    "Honesty",
    "Responsible",
    "Accountability",
    "Understanding",
    "Self Worth",
    "Virtue",
    "Reasonable",
    "Goodness",
    "Good Natured",
    "Morality",
    "Respect",
    "Thoughtful",
    "Self-control",
    "Methodical",
    "Mindfulness",
    "Prioritization",
    "Good Friend",
    "Self-awareness",
    "Mentality"
]);

// var Leadership = [];
// [...tags.keys()].forEach((key) => {
//     Leadership.push(String(key));
// });
 
values_list.set("Love", [
    "Amiability",
    "Interpersonal",
    "Amiable Love",
    "Prioritization",
    "Good Deed",
    "Flexibility",
    "Kindness",
    "Forgiveness",
    "Patience",
    "Thoughtful",
    "Empathy",
    "Caring",
    "Communication",
    "Service",
    "Appreciation",
    "Sympathetic",
    "Grateful",
    "Humble",
    "Comfort",
    "Preservation",
    "Trust",
    "Loyalty",
    "Generous",
    "Provision",
    "Proactive",
    "External Awareness",
    "Presentation",
    "Intimacy",
    "Mindfulness"
]);

values_list.set("Loyalty", [
    "Core Values",
    "Maintenance",
    "Proactive",
    "Impervious",
    "Focus",
    "Preservation",
    "Loyalty",
    "Trust",
    "Pride",
    "Strong Will",
    "Virtue",
    "Service",
    "Dedication",
    "Faithfulness",
    "Respect",
    "Thoughtful",
    "Mindfulness",
    "Mindset",
    "Resilience"
]);

values_list.set("Optimism", [
    "Optimism",
    "Mentality",
    "Resilience",
    "Emotion Control",
    "Self-awareness",
    "Emotional Intelligence",
    "Visionary",
    "Social Awareness",
    "Good Deed",
    "Mindfulness",
    "Patience",
    "Thoughtful",
    "Situational Awareness",
    "Pragmaticism",
    "Psychology",
    "Charisma",
    "Good Natured",
    "Innovative",
    "Love of Challenge",
    "Forward Thinking",
    "Faithfulness",
    "Grounded",
    "Agreeable",
    "Appreciation",
    "Leadership",
    "Perseverence",
    "Growth",
    "Exploration",
    "Progress",
    "Inspiration",
    "Trust",
    "Understanding",
    "Learning",
    "Transcendant",
    "Impervious",
    "Proactive",
    "Information Processing"
]);

values_list.set("Nature", [
    "Spiritual",
    "Reality",
    "Aesthetic",
    "Survival",
    "External Awareness",
    "Transcendant",
    "Resourceful",
    "Curiosity",
    "Happiness",
    "Preservation",
    "Comfort",
    "Exploration",
    "Appreciation",
    "Nature",
    "Grounded",
    "Respect",
    "Contentment",
    "Mindfulness",
    "Fulfillment"
]);

values_list.set("Patriotism", [
    "Positive Influence",
    "Mentality",
    "Assertion",
    "Visionary",
    "Social Awareness",
    "Society",
    "Humanitarian",
    "Mindfulness",
    "Planning",
    "Thoughtful",
    "Situational Awareness",
    "Analytical",
    "Empahty",
    "Considerate",
    "Good Natured",
    "Modernized",
    "Peace",
    "Goodness",
    "Faithfulness",
    "History",
    "Dedication",
    "Service",
    "Harmonious",
    "Problem Solving",
    "Traditionalism",
    "Virtue",
    "Execution",
    "Perseverence",
    "Passion",
    "Legacy",
    "Pride",
    "Success",
    "Enabler",
    "Inspiration",
    "Preservation",
    "Loyalty",
    "Accountability",
    "Responsible",
    "Open-mindedness",
    "Generous",
    "Courage",
    "Systematic",
    "Honesty",
    "Purpose",
    "Provision",
    "Extraspection",
    "Risk Management",
    "Resourceful",
    "Moderation",
    "Impervious",
    "Proactive",
    "External Awareness",
    "Maintenance",
    "Acceptance",
    "Responsive",
    "Core Values"
]);

values_list.set("Patience", [
    "Core Values",
    "Ethics",
    "Practice",
    "Responsive",
    "Acceptance",
    "External Awareness",
    "Life Skills",
    "Information Processing",
    "Proactive",
    "Impervious",
    "Moderation",
    "Stoicism",
    "Extraspection",
    "Open-mindedness",
    "Understanding",
    "Preservation",
    "Humble",
    "Perseverence",
    "Virtue",
    "Agreeable",
    "Harmonious",
    "Communication",
    "Discipline",
    "Grounded",
    "Reasonable",
    "Maturity",
    "Peace",
    "Good Natured",
    "Friendly",
    "Conversationalist",
    "Considerate",
    "Gentleness",
    "Respect",
    "Situational Awareness",
    "Thoughtful",
    "Patience",
    "Self-control",
    "Mindfulness",
    "Mindset",
    "Amiable Love",
    "Social Awareness",
    "Emotional Intelligence",
    "Self-awareness",
    "Interpersonal"
]);

values_list.set("Perseverence", [
    "Optimism",
    "Mentality",
    "Resilience",
    "Emotion Control",
    "Self-awareness",
    "Mindfulness",
    "Methodical",
    "Self-control",
    "Planning",
    "Patience",
    "Thoughtful",
    "Situational Awareness",
    "Pragmaticism",
    "Psychology",
    "Self-confidence",
    "Anxiety Control",
    "Forward Thinking",
    "Grounded",
    "Productive",
    "Dedication",
    "Discipline",
    "Execution",
    "Time Management",
    "Self Worth",
    "Perseverence",
    "Motivation",
    "Strong Will",
    "Loyalty",
    "Accountability",
    "Responsible",
    "Focus",
    "Purpose",
    "Resourceful",
    "Impervious",
    "Proactive",
    "Responsive"
]);

values_list.set("Power", [
    "High Standards",
    "Core Values",
    "Presentation",
    "Responsive",
    "Maintenance",
    "External Awareness",
    "Self-worth",
    "Proactive",
    "Impervious",
    "Moderation",
    "Resourceful",
    "Stoicism",
    "Inductive Reasoning",
    "Risk Management",
    "Extraspection",
    "Work Ethic",
    "Systematic",
    "Courage",
    "Open-mindedness",
    "Focus",
    "Accountability",
    "Preservation",
    "Deductive Reasoning",
    "Creative",
    "Success",
    "Pride",
    "Strong Will",
    "Passion",
    "Meticulous",
    "Perseverence",
    "Time Management",
    "Leadership",
    "Execution",
    "Communication",
    "Discipline",
    "Independence",
    "Forward Thinking",
    "Love of Challenge",
    "Innovative",
    "Retrospective",
    "Anxiety Control",
    "Eloquent",
    "Entertaining",
    "Interesting",
    "Uniqueness",
    "Self-confidence",
    "Psychology",
    "Thoughtful",
    "Patience",
    "Planning",
    "Self-control",
    "Methodical",
    "Mindset",
    "Prioritization",
    "Social Awareness",
    "Self-care",
    "Visionary",
    "Emotional Intelligence",
    "Introspection",
    "Assertion",
    "Self-awareness",
    "Social Network",
    "Amiability",
    "Socialization",
    "Emotion Control",
    "Resilience",
    "Mentality"
]);

values_list.set("Pride", [
    "Mentality",
    "Resilience",
    "Emotion Control",
    "Self-awareness",
    "Assertion",
    "Introspection",
    "Self-care",
    "Prioritization",
    "Self-control",
    "Thoughtful",
    "Respect",
    "Self-confidence",
    "Charisma",
    "Anxiety Control",
    "Love of Challenge",
    "Independence",
    "Dedication",
    "Self-love",
    "Execution",
    "Self Worth",
    "Passion",
    "Strong Will",
    "Pride",
    "Legacy",
    "Success",
    "Courage",
    "Aesthetic",
    "Presentation",
    "High Standards",
]);

values_list.set("Reliability", [
    "High Standards",
    "Core Values",
    "Practice",
    "Maintenance",
    "External Awareness",
    "Self-worth",
    "Proactive",
    "Risk Management",
    "Extraspection",
    "Work Ethic",
    "Systematic",
    "Focus",
    "Responsible",
    "Accountability",
    "Understanding",
    "Preservation",
    "Inductive Reasoning",
    "Thorough",
    "Meticulous",
    "Perseverence",
    "Time Management",
    "Execution",
    "Discipline",
    "Dedication",
    "Performance",
    "Analytical",
    "Thoughtful",
    "Planning",
    "Methodical",
    "Mindfulness",
    "Mindset",
    "Prioritization",
    "Self-awareness",
    "Resilience"
]);

values_list.set("Self-expression", [
    "Mentality",
    "Emotion Control",
    "Socialization",
    "Self-awareness",
    "Assertion",
    "Self-care",
    "Prioritization",
    "Fulfillment",
    "Thoughtful",
    "Self-confidence",
    "Uniqueness",
    "Interesting",
    "Emotional Intelligence",
    "Charisma",
    "Interesting",
    "Eloquent",
    "Independence",
    "Self-love",
    "Communication",
    "Self Worth",
    "Preservation",
    "Happiness",
    "Understanding",
    "Courage",
    "Authentic",
    "Lively",
    "Aesthetic",
    "Maintenance",
    "Presentation"
]);

values_list.set("Success", [
    "High Standards",
    "Practice",
    "External Awareness",
    "Proactive",
    "Impervious",
    "Resourceful",
    "Learning",
    "Inductive Reasoning",
    "Deductive Reasoning",
    "Risk Management",
    "Extraspection",
    "Work Ethic",
    "Systematic",
    "Open-mindedness",
    "Focus",
    "Responsible",
    "Accountability",
    "Understanding",
    "Loyalty",
    "Preservation",
    "Humble",
    "Creativity",
    "Success",
    "Thorough",
    "Strong Will",
    "Perseverence",
    "Time Management",
    "Execution",
    "Discipline",
    "Dedication",
    "Independence",
    "Performance",
    "Financial Literacy",
    "Forward Thinking",
    "Love of Challenge",
    "Innovative",
    "Anxiety Control",
    "Uniqueness",
    "Charisma",
    "Self-confidence",
    "Analytical",
    "Thoughtful",
    "Patience",
    "Planning",
    "Self-control",
    "Methodical",
    "Mindfulness",
    "Prioritization",
    "Visionary",
    "Self-care",
    "Introspection",
    "Assertion",
    "Self-awareness",
    "Interpersonal",
    "Emotion Control",
    "Resilience",
    "Optimism",
    "Mentality",
    "Positive Influence"
]);

values_list.set("Tradition", [
    "Mentality",
    "Resilience",
    "Prioritization",
    "Society",
    "Mindfulness",
    "Self-control",
    "Methodical",
    "Thoughtful",
    "Situational Awareness",
    "Respect",
    "Peace",
    "History",
    "Grounded",
    "Dedication",
    "Traditionalism",
    "Virtue",
    "Legacy",
    "Trust",
    "Preservation",
    "Loyalty",
    "Acountability",
    "Systematic",
    "Risk Management",
    "Moderation",
    "Impervious",
    "Maintenance",
    "Core Values"
]);

values_list.set("Change", [
    "Responsive",
    "External Awareness",
    "Diverse",
    "Proactive",
    "Resourceful",
    "Curiousity",
    "Deductive Reasoning",
    "Inductive Reasoning",
    "Extraspection",
    "Systematic",
    "Courage",
    "Open-mindedness",
    "Progress",
    "Legacy",
    "Exploration",
    "Growth",
    "Execution",
    "Dedication",
    "Innovative",
    "Retrospective",
    "Spontaneity",
    "Thoughtful",
    "Planning",
    "Methodical",
    "Change",
    "Mindfulness",
    "Flexibility",
    "Society",
    "Mindset",
    "Prioritization",
    "Assertion",
    "Positive Influence",
    "Resilience"
]);

values_list.set("Truth", [
    "Positive Influence",
    "Mentality",
    "Interpersonal",
    "Emotional Intelligence",
    "Mindset",
    "Good Deed",
    "Mindfulness",
    "Kindness",
    "Self-control",
    "Thoughtful",
    "Respect",
    "Analytical",
    "Retrospective",
    "Introspective",
    "Grounded",
    "Dedicated",
    "Agreeable",
    "Virtue",
    "Exploration",
    "Thorough",
    "Understanding",
    "Open-mindedness",
    "Impervious",
    "Courage",
    "Honesty",
    "Learning",
    "Proactive",
    "Information Processing",
    "How or Why",
    "Core Values"
]);

values_list.set("Trust", [
    "Moderation",
    "Risk Management",
    "Understanding",
    "Loyalty",
    "Trust",
    "Humble",
    "Grateful",
    "Strong Will",
    "Perseverence",
    "Appreciation",
    "Dedication",
    "Grounded",
    "Faithfulness",
    "Anxiety Control",
    "Self-confidence",
    "Thoughtful",
    "Patience",
    "Self-control",
    "Contentment",
    "Mindset",
    "Visionary",
    "Resilience",
    "Optimism"
]);

export { values_list };