# Generated by Django 6.0.7 on 2026-07-24 03:56

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CurriculumVersion",
            fields=[
                ("stable_id", models.CharField(max_length=80, primary_key=True, serialize=False)),
                ("curriculum_version", models.CharField(max_length=80)),
                ("model_version", models.CharField(max_length=40)),
                ("assessment_version", models.CharField(max_length=40)),
                ("source_hash", models.CharField(max_length=64)),
                ("active", models.BooleanField(default=True)),
                ("imported_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["stable_id"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentRun",
            fields=[
                ("stable_id", models.CharField(max_length=80, primary_key=True, serialize=False)),
                ("assessment_version", models.CharField(max_length=40)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("application", "Application"),
                            ("share_code", "Share code"),
                            ("pilot_seed", "Pilot seed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("answers", models.JSONField(default=dict)),
                ("clarifier_answers", models.JSONField(default=dict)),
                ("timing_data", models.JSONField(default=dict)),
                ("response_quality_result", models.JSONField(default=dict)),
                ("orientation_outputs", models.JSONField(default=dict)),
                ("archetype_outputs", models.JSONField(default=list)),
                ("raw_lever_scores", models.JSONField(default=dict)),
                ("calibrated_lever_estimates", models.JSONField(default=dict)),
                ("lever_confidence", models.JSONField(default=dict)),
                ("original_share_code", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "curriculum_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_runs",
                        to="growth.curriculumversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Competency",
            fields=[
                ("stable_id", models.CharField(max_length=8, primary_key=True, serialize=False)),
                ("domain_id", models.CharField(max_length=8)),
                ("domain_name", models.CharField(max_length=180)),
                ("name", models.CharField(max_length=220)),
                ("scope", models.TextField()),
                ("evidence_of_progress", models.TextField()),
                ("applicability", models.CharField(max_length=80)),
                ("normative_status", models.CharField(max_length=100)),
                ("formation_modes", models.JSONField(default=list)),
                ("preferred_evidence_types", models.JSONField(default=list)),
                ("professional_boundary", models.TextField(blank=True)),
                (
                    "curriculum_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competencies",
                        to="growth.curriculumversion",
                    ),
                ),
            ],
            options={
                "ordering": ["stable_id"],
            },
        ),
        migrations.CreateModel(
            name="Lever",
            fields=[
                ("stable_id", models.CharField(max_length=8, primary_key=True, serialize=False)),
                ("slug", models.SlugField(max_length=100)),
                ("name", models.CharField(max_length=180)),
                ("family_id", models.CharField(max_length=8)),
                ("family_slug", models.SlugField(max_length=100)),
                ("family_name", models.CharField(max_length=140)),
                ("definition", models.TextField()),
                ("orientation_composition", models.JSONField(default=dict)),
                ("competency_count", models.PositiveSmallIntegerField()),
                ("total_competency_weight", models.DecimalField(decimal_places=4, max_digits=8)),
                (
                    "curriculum_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="levers",
                        to="growth.curriculumversion",
                    ),
                ),
            ],
            options={
                "ordering": ["stable_id"],
            },
        ),
        migrations.CreateModel(
            name="PracticeProtocol",
            fields=[
                ("stable_id", models.CharField(max_length=80, primary_key=True, serialize=False)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=180)),
                (
                    "availability",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="inactive",
                        max_length=10,
                    ),
                ),
                ("duration_days", models.PositiveSmallIntegerField()),
                ("recommendation_reason", models.TextField()),
                ("applicability_prompt", models.TextField()),
                ("setup_prompt", models.TextField()),
                ("privacy_and_boundaries", models.TextField()),
                ("completion_criteria", models.JSONField(default=list)),
                (
                    "mastery_disclaimer",
                    models.CharField(
                        default="Completing this practice does not establish mastery.",
                        max_length=120,
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "target_levers",
                    models.ManyToManyField(related_name="practice_protocols", to="growth.lever"),
                ),
            ],
            options={
                "ordering": ["display_order", "stable_id"],
            },
        ),
        migrations.CreateModel(
            name="PracticeAction",
            fields=[
                ("stable_id", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("sequence", models.PositiveSmallIntegerField()),
                ("title", models.CharField(max_length=180)),
                ("instructions", models.TextField()),
                ("due_within_days", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="growth.practiceprotocol",
                    ),
                ),
            ],
            options={
                "ordering": ["protocol_id", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="PracticeSprint",
            fields=[
                (
                    "stable_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("person_or_context", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("stopped", "Stopped"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assessment_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="practice_sprints",
                        to="growth.assessmentrun",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sprints",
                        to="growth.practiceprotocol",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_sprints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PracticeReview",
            fields=[
                (
                    "stable_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("actions_attempted", models.PositiveSmallIntegerField(default=0)),
                ("actions_completed", models.PositiveSmallIntegerField(default=0)),
                ("substantive_interaction_occurred", models.BooleanField(default=False)),
                ("reflection", models.TextField()),
                ("contradictory_evidence", models.TextField(blank=True)),
                ("static_score_impact_preview", models.JSONField(default=dict)),
                (
                    "mastery_disclaimer",
                    models.CharField(
                        default="Completing this practice does not establish mastery.",
                        max_length=120,
                    ),
                ),
                ("submitted_at", models.DateTimeField()),
                (
                    "sprint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="growth.practicesprint",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PracticeCheckIn",
            fields=[
                (
                    "stable_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("submitted", "Submitted")],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("action_attempted", models.BooleanField(default=False)),
                ("action_completed", models.BooleanField(default=False)),
                ("user_initiated", models.BooleanField(default=False)),
                ("moved_beyond_transactional", models.BooleanField(default=False)),
                ("follow_up_question_asked", models.BooleanField(default=False)),
                ("meaningful_information_shared", models.BooleanField(default=False)),
                ("future_interaction_scheduled", models.BooleanField(default=False)),
                ("follow_up_within_seven_days", models.BooleanField(default=False)),
                (
                    "internal_resistance",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "expected_reciprocity",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "observed_reciprocity",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                ("contradictory_evidence", models.TextField(blank=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="check_ins",
                        to="growth.practiceaction",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_ins",
                        to="growth.practicesprint",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArchetypeResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("stable_id", models.CharField(max_length=8)),
                ("name", models.CharField(max_length=120)),
                ("orientation_slugs", models.JSONField(default=list)),
                ("fit_index", models.DecimalField(decimal_places=4, max_digits=6)),
                (
                    "fit_confidence",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
                ),
                ("rank", models.PositiveSmallIntegerField()),
                (
                    "assessment_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archetype_results",
                        to="growth.assessmentrun",
                    ),
                ),
            ],
            options={
                "ordering": ["rank", "stable_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("assessment_run", "stable_id"),
                        name="unique_archetype_per_assessment",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CompetencyLeverLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    "competency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lever_links",
                        to="growth.competency",
                    ),
                ),
                (
                    "lever",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competency_links",
                        to="growth.lever",
                    ),
                ),
            ],
            options={
                "ordering": ["competency_id", "-weight", "lever_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("competency", "lever"), name="unique_competency_lever_link"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("weight__gt", 0), ("weight__lte", 1)),
                        name="competency_lever_weight_in_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LeverBaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("raw_self_report", models.DecimalField(decimal_places=4, max_digits=6)),
                ("calibrated_estimate", models.DecimalField(decimal_places=4, max_digits=6)),
                ("evidence_confidence", models.DecimalField(decimal_places=4, max_digits=6)),
                ("need_score", models.DecimalField(decimal_places=4, max_digits=6)),
                ("need_rank", models.PositiveSmallIntegerField()),
                ("notes", models.TextField(blank=True)),
                (
                    "assessment_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lever_baselines",
                        to="growth.assessmentrun",
                    ),
                ),
                (
                    "lever",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="baselines",
                        to="growth.lever",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lever_baselines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["need_rank", "lever_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("assessment_run", "lever"),
                        name="unique_lever_baseline_per_assessment",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OrientationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("stable_id", models.CharField(max_length=8)),
                ("slug", models.SlugField(max_length=80)),
                ("name", models.CharField(max_length=120)),
                ("score", models.DecimalField(decimal_places=4, max_digits=6)),
                ("confidence", models.DecimalField(decimal_places=4, max_digits=6)),
                (
                    "assessment_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orientation_results",
                        to="growth.assessmentrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "stable_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("assessment_run", "stable_id"),
                        name="unique_orientation_per_assessment",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="practiceaction",
            constraint=models.UniqueConstraint(
                fields=("protocol", "sequence"), name="unique_action_sequence_per_protocol"
            ),
        ),
    ]
