# Generated by Django 6.0.7 on 2026-07-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("growth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicesprint",
            name="boundaries_acknowledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="practicesprint",
            name="setup_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="leverbaseline",
            name="calibrated_estimate",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name="leverbaseline",
            name="need_score",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name="leverbaseline",
            name="raw_self_report",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddConstraint(
            model_name="practicecheckin",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("action_completed", False), ("action_attempted", True), _connector="OR"
                ),
                name="completed_check_in_requires_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="practicecheckin",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "draft"), ("submitted_at__isnull", True)),
                    models.Q(("status", "submitted"), ("submitted_at__isnull", False)),
                    _connector="OR",
                ),
                name="check_in_submission_timestamp_matches_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="practicesprint",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["active", "paused"])),
                fields=("user",),
                name="one_current_practice_per_user",
            ),
        ),
    ]
