# Generated by Django 6.0.7 on 2026-07-24 06:11

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("growth", "0002_m1b_workflow_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceEvent",
            fields=[
                (
                    "stable_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("algorithm_version", models.CharField(max_length=40)),
                ("protocol_stable_id", models.CharField(max_length=80)),
                ("action_stable_id", models.CharField(max_length=100)),
                ("input_snapshot", models.JSONField()),
                (
                    "performance",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "quality",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "independence",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "context_breadth",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("repetition_index", models.PositiveSmallIntegerField()),
                (
                    "repetition_multiplier",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "contradiction_level",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "base_evidence_mass",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("explanation", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["check_in__submitted_at", "stable_id"],
            },
        ),
        migrations.AddField(
            model_name="practiceaction",
            name="evidence_rules",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="practicecheckin",
            name="context_comparison",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first_record", "First record for this practice"),
                    ("same_context", "Similar setting or situation"),
                    ("varied_context", "Meaningfully different setting or situation"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="practicecheckin",
            name="evidence_direction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("supports", "Supported the expected pattern"),
                    ("mixed", "Mixed or unclear"),
                    ("contradicts", "Contradicted the expected pattern"),
                    ("inconclusive", "Not enough happened to tell"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="practicecheckin",
            name="support_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("independent", "Self-directed"),
                    ("planning_aid", "Used a reminder or planning aid"),
                    ("guided", "Needed real-time prompting or guidance"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="practicecheckin",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("evidence_direction__in", ["mixed", "contradicts"]), _negated=True),
                    models.Q(("contradictory_evidence", ""), _negated=True),
                    _connector="OR",
                ),
                name="directed_contradiction_requires_detail",
            ),
        ),
        migrations.AddField(
            model_name="evidenceevent",
            name="check_in",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence_event",
                to="growth.practicecheckin",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("repetition_index__gte", 1)),
                name="evidence_repetition_index_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("performance__gte", 0), ("performance__lte", 1)),
                name="evidence_performance_in_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("quality__gte", 0), ("quality__lte", 1)),
                name="evidence_quality_in_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("independence__gte", 0), ("independence__lte", 1)),
                name="evidence_independence_in_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("context_breadth__gte", 0), ("context_breadth__lte", 1)),
                name="evidence_context_breadth_in_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("repetition_multiplier__gt", 0), ("repetition_multiplier__lte", 1)
                ),
                name="evidence_repetition_multiplier_in_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("contradiction_level__isnull", True),
                    models.Q(("contradiction_level__gte", 0), ("contradiction_level__lte", 1)),
                    _connector="OR",
                ),
                name="evidence_contradiction_level_in_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_evidence_mass__gte", 0), ("base_evidence_mass__lte", 1)),
                name="evidence_base_mass_in_range",
            ),
        ),
    ]
