# Generated by Django 6.0.7 on 2026-07-27 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("growth", "0003_m2a_evidence_events"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="leverbaseline",
            name="baseline_alpha",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="leverbaseline",
            name="baseline_beta",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="leverbaseline",
            name="baseline_mass_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("canonical_result", "Canonical assessment result"),
                    ("published_reconstruction", "Reconstructed from published rounded values"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="practiceprotocol",
            name="parent_competency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="practice_protocols",
                to="growth.competency",
            ),
        ),
        migrations.AddConstraint(
            model_name="leverbaseline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("baseline_alpha__isnull", True),
                        ("baseline_beta__isnull", True),
                        ("baseline_mass_source", ""),
                    ),
                    models.Q(
                        ("baseline_alpha__isnull", False),
                        ("baseline_beta__isnull", False),
                        models.Q(("baseline_mass_source", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="lever_baseline_mass_state_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="leverbaseline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("baseline_alpha__isnull", True), ("baseline_alpha__gte", 0), _connector="OR"
                ),
                name="lever_baseline_alpha_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="leverbaseline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("baseline_beta__isnull", True), ("baseline_beta__gte", 0), _connector="OR"
                ),
                name="lever_baseline_beta_nonnegative",
            ),
        ),
    ]
