# Generated by Django 6.0.7 on 2026-07-27 17:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("growth", "0004_m3a_shadow_scoring"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeverState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("algorithm_version", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Evidence updates available"),
                            ("baseline_only", "Baseline only"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "current_alpha",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
                ),
                (
                    "current_beta",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
                ),
                (
                    "current_estimate",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
                ),
                ("current_confidence", models.DecimalField(decimal_places=4, max_digits=6)),
                (
                    "cumulative_evidence_mass",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                ("included_evidence_events", models.PositiveIntegerField(default=0)),
                (
                    "current_need_score",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
                ),
                ("current_need_rank", models.PositiveSmallIntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lever_states",
                        to="growth.assessmentrun",
                    ),
                ),
                (
                    "baseline",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_state",
                        to="growth.leverbaseline",
                    ),
                ),
                (
                    "lever",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="states",
                        to="growth.lever",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lever_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["current_need_rank", "lever_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("assessment_run", "lever"), name="unique_lever_state_per_assessment"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("current_alpha__isnull", True), ("current_beta__isnull", True)
                            ),
                            models.Q(
                                ("current_alpha__isnull", False), ("current_beta__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="lever_state_mass_pair_complete",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("current_alpha__isnull", True),
                            ("current_alpha__gte", 0),
                            _connector="OR",
                        ),
                        name="lever_state_alpha_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("current_beta__isnull", True),
                            ("current_beta__gte", 0),
                            _connector="OR",
                        ),
                        name="lever_state_beta_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("cumulative_evidence_mass__gte", 0)),
                        name="lever_state_evidence_mass_nonnegative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScoreSnapshot",
            fields=[
                (
                    "stable_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("initialize", "Initialize baseline state"),
                            ("process", "Process evidence event"),
                            ("reverse", "Reverse evidence event"),
                            ("rebuild", "Repair current state from event history"),
                        ],
                        max_length=12,
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("algorithm_version", models.CharField(max_length=40)),
                ("state_schema_version", models.CharField(max_length=40)),
                ("before_state", models.JSONField(blank=True, default=list)),
                ("after_state", models.JSONField(blank=True, default=list)),
                ("contribution_snapshot", models.JSONField(blank=True, default=dict)),
                ("active_event_count", models.PositiveIntegerField(default=0)),
                ("active_event_hash", models.CharField(max_length=64)),
                ("before_state_hash", models.CharField(max_length=64)),
                ("after_state_hash", models.CharField(max_length=64)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="score_snapshots",
                        to="growth.assessmentrun",
                    ),
                ),
                (
                    "evidence_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="score_snapshots",
                        to="growth.evidenceevent",
                    ),
                ),
            ],
            options={
                "ordering": ["assessment_run_id", "sequence"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("assessment_run", "sequence"), name="unique_score_snapshot_sequence"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("operation", "initialize")),
                        fields=("assessment_run",),
                        name="unique_score_state_initialization",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("operation", "process")),
                        fields=("evidence_event",),
                        name="unique_score_event_processing",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("operation", "reverse")),
                        fields=("evidence_event",),
                        name="unique_score_event_reversal",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("evidence_event__isnull", False),
                                ("operation__in", ["process", "reverse"]),
                            ),
                            models.Q(
                                ("evidence_event__isnull", True),
                                ("operation__in", ["initialize", "rebuild"]),
                            ),
                            _connector="OR",
                        ),
                        name="score_snapshot_event_matches_operation",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("operation", "reverse"), _negated=True),
                            models.Q(("reason", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="score_reversal_requires_reason",
                    ),
                ],
            },
        ),
    ]
