# Generated by Django 6.0.7 on 2026-07-27 21:40

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("growth", "0006_m4a_protocol_library"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PilotFeedback",
            fields=[
                (
                    "stable_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contract_version",
                    models.CharField(
                        default="GG-PILOT-FEEDBACK-1.0",
                        editable=False,
                        max_length=40,
                    ),
                ),
                (
                    "journey_stage",
                    models.CharField(
                        choices=[
                            ("login", "Signing in"),
                            ("assessment", "Taking or importing the assessment"),
                            ("profile", "Understanding the profile"),
                            ("recommendation", "Choosing a recommended practice"),
                            ("setup", "Setting up a practice"),
                            ("active_practice", "Using an active practice"),
                            ("check_in", "Submitting a check-in"),
                            ("review", "Completing the final review"),
                            ("account", "Account settings"),
                            ("other", "Another part of the experience"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "applicability",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "It fit my current situation"),
                            ("partly", "It partly fit"),
                            ("no", "It did not fit my current situation"),
                            ("unsure", "I was unsure"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                (
                    "time_to_start",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("under_2_minutes", "Under 2 minutes"),
                            ("2_to_5_minutes", "2-5 minutes"),
                            ("over_5_minutes", "More than 5 minutes"),
                            ("not_started", "I did not start"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "time_to_check_in",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("under_1_minute", "Under 1 minute"),
                            ("1_to_2_minutes", "1-2 minutes"),
                            ("over_2_minutes", "More than 2 minutes"),
                            ("not_completed", "I did not complete a check-in"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "confusing_step",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "Nothing was confusing"),
                            ("login", "Signing in"),
                            ("assessment", "Assessment questions or import"),
                            ("profile", "Profile language"),
                            ("recommendation", "Why a practice was recommended"),
                            ("setup", "Practice setup"),
                            ("actions", "Practice action instructions"),
                            ("check_in", "Check-in questions"),
                            ("review", "Final review or completion"),
                            ("account", "Account settings"),
                            ("other", "Another step"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "accessibility_friction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "No"),
                            ("present", "Yes"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "safety_friction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "No"),
                            ("present", "Yes"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        validators=[django.core.validators.MaxLengthValidator(1000)],
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "protocol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pilot_feedback",
                        to="growth.practiceprotocol",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pilot_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["submitted_at", "stable_id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("contract_version", "GG-PILOT-FEEDBACK-1.0")),
                        name="pilot_feedback_contract_version_v1",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("accessibility_friction", ""),
                            ("applicability", ""),
                            ("comment", ""),
                            ("confusing_step", ""),
                            ("safety_friction", ""),
                            ("time_to_check_in", ""),
                            ("time_to_start", ""),
                            _negated=True,
                        ),
                        name="pilot_feedback_has_signal",
                    ),
                ],
            },
        ),
    ]
