# Generated by Django 6.0.8 on 2026-08-13

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

VALUE_STATES = ["unknown", "not_applicable", "deferred", "provided"]
PRACTICE_FACTORS = [
    "applicability",
    "importance",
    "readiness",
    "urgency",
    "opportunity_resources",
    "burden",
]


def _practice_constraints():
    constraints = [
        models.UniqueConstraint(
            fields=("assessment_run", "protocol", "revision"),
            name="unique_practice_context_revision",
        ),
        models.CheckConstraint(
            condition=models.Q(contract_version="GG-CONTEXT-1.0"),
            name="practice_context_contract_v1",
        ),
        models.CheckConstraint(
            condition=models.Q(revision__gte=1),
            name="practice_context_revision_positive",
        ),
        models.CheckConstraint(
            condition=models.Q(disposition__in=["considering", "deferred"]),
            name="practice_context_disposition_valid",
        ),
        models.CheckConstraint(
            condition=models.Q(defer_reason="")
            | models.Q(
                defer_reason__in=[
                    "capacity",
                    "resources",
                    "timing",
                    "safety_or_access",
                    "role_or_fit",
                    "competing_priority",
                    "needs_support",
                    "user_choice",
                ]
            ),
            name="practice_context_defer_reason_valid",
        ),
        models.CheckConstraint(
            condition=models.Q(review_horizon_days__isnull=True)
            | models.Q(review_horizon_days__gte=1, review_horizon_days__lte=366),
            name="practice_context_review_horizon_in_range",
        ),
    ]
    for field_name in PRACTICE_FACTORS:
        constraints.extend(
            [
                models.CheckConstraint(
                    condition=models.Q(**{f"{field_name}_state__in": VALUE_STATES}),
                    name=f"practice_context_{field_name}_state_valid",
                ),
                models.CheckConstraint(
                    condition=(
                        models.Q(**{f"{field_name}_state": "provided"})
                        & models.Q(**{f"{field_name}_value__isnull": False})
                        | ~models.Q(**{f"{field_name}_state": "provided"})
                        & models.Q(**{f"{field_name}_value__isnull": True})
                    ),
                    name=f"practice_context_{field_name}_value_state",
                ),
                models.CheckConstraint(
                    condition=models.Q(**{f"{field_name}_value__isnull": True})
                    | models.Q(
                        **{
                            f"{field_name}_value__gte": 0,
                            f"{field_name}_value__lte": 4,
                        }
                    ),
                    name=f"practice_context_{field_name}_value_range",
                ),
            ]
        )
    constraints.append(
        models.CheckConstraint(
            condition=(
                models.Q(disposition="deferred")
                & ~models.Q(defer_reason="")
                & (
                    models.Q(applicability_state="deferred")
                    | models.Q(importance_state="deferred")
                    | models.Q(readiness_state="deferred")
                    | models.Q(urgency_state="deferred")
                    | models.Q(opportunity_resources_state="deferred")
                    | models.Q(burden_state="deferred")
                )
                | models.Q(disposition="considering")
                & models.Q(defer_reason="")
                & models.Q(review_horizon_days__isnull=True)
                & ~models.Q(applicability_state="deferred")
                & ~models.Q(importance_state="deferred")
                & ~models.Q(readiness_state="deferred")
                & ~models.Q(urgency_state="deferred")
                & ~models.Q(opportunity_resources_state="deferred")
                & ~models.Q(burden_state="deferred")
            ),
            name="practice_context_defer_metadata_consistent",
        )
    )
    return constraints


class Migration(migrations.Migration):
    dependencies = [
        ("growth", "0007_pilotfeedback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentContext",
            fields=[
                (
                    "stable_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contract_version",
                    models.CharField(
                        default="GG-CONTEXT-1.0",
                        editable=False,
                        max_length=40,
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                (
                    "season_state",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("not_applicable", "Not applicable"),
                            ("deferred", "Deferred"),
                            ("provided", "Provided"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "season_value",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("foundation", "Foundation"),
                            ("expansion", "Expansion"),
                            ("maintenance", "Maintenance"),
                            ("transition", "Transition"),
                            ("recovery", "Recovery"),
                            ("caregiving", "Caregiving"),
                            ("constraint", "Constraint"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "capacity_state",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("not_applicable", "Not applicable"),
                            ("deferred", "Deferred"),
                            ("provided", "Provided"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "capacity_value",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                ("canonical_snapshot", models.JSONField()),
                ("content_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="context_records",
                        to="growth.assessmentrun",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_context_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["assessment_run_id", "revision"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("assessment_run", "revision"),
                        name="unique_assessment_context_revision",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(contract_version="GG-CONTEXT-1.0"),
                        name="assessment_context_contract_v1",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(revision__gte=1),
                        name="assessment_context_revision_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(season_state__in=VALUE_STATES),
                        name="assessment_context_season_state_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(capacity_state__in=VALUE_STATES),
                        name="assessment_context_capacity_state_valid",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(season_state="provided") & ~models.Q(season_value="")
                            | ~models.Q(season_state="provided") & models.Q(season_value="")
                        ),
                        name="assessment_context_season_value_matches_state",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(capacity_state="provided")
                            & models.Q(capacity_value__isnull=False)
                            | ~models.Q(capacity_state="provided")
                            & models.Q(capacity_value__isnull=True)
                        ),
                        name="assessment_context_capacity_value_matches_state",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(capacity_value__isnull=True)
                        | models.Q(capacity_value__gte=0, capacity_value__lte=4),
                        name="assessment_context_capacity_in_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PracticeContext",
            fields=[
                (
                    "stable_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contract_version",
                    models.CharField(
                        default="GG-CONTEXT-1.0",
                        editable=False,
                        max_length=40,
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                *[
                    field
                    for factor_id in PRACTICE_FACTORS
                    for field in (
                        (
                            f"{factor_id}_state",
                            models.CharField(
                                choices=[
                                    ("unknown", "Unknown"),
                                    ("not_applicable", "Not applicable"),
                                    ("deferred", "Deferred"),
                                    ("provided", "Provided"),
                                ],
                                max_length=20,
                            ),
                        ),
                        (
                            f"{factor_id}_value",
                            models.PositiveSmallIntegerField(blank=True, null=True),
                        ),
                    )
                ],
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("considering", "Considering"),
                            ("deferred", "Deferred / not now"),
                        ],
                        default="considering",
                        max_length=20,
                    ),
                ),
                (
                    "defer_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("capacity", "Capacity"),
                            ("resources", "Resources"),
                            ("timing", "Timing"),
                            ("safety_or_access", "Safety or access"),
                            ("role_or_fit", "Role or fit"),
                            ("competing_priority", "Competing priority"),
                            ("needs_support", "Needs support"),
                            ("user_choice", "User choice"),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                (
                    "review_horizon_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(366),
                        ],
                    ),
                ),
                ("canonical_snapshot", models.JSONField()),
                ("content_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="practice_context_records",
                        to="growth.assessmentrun",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="context_records",
                        to="growth.practiceprotocol",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_context_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["assessment_run_id", "protocol_id", "revision"],
                "constraints": _practice_constraints(),
            },
        ),
    ]
