# Generated by Django 6.0.8 on 2026-08-13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

VALUE_STATES = ["unknown", "not_applicable", "deferred", "provided"]
SCALAR_SECTIONS = [
    "mission",
    "twelve_month_direction",
    "current_truth",
    "autopilot_pattern",
    "misalignment_or_fragmentation",
    "deliberate_next_step",
]
LIST_SECTIONS = ["principles", "anti_goals", "priority_stack"]


def _constraints():
    constraints = [
        models.UniqueConstraint(
            fields=("assessment_run", "revision"),
            name="unique_personal_os_revision",
        ),
        models.CheckConstraint(
            condition=models.Q(contract_version="GG-PERSONAL-OS-1.0"),
            name="personal_os_contract_v1",
        ),
        models.CheckConstraint(
            condition=models.Q(revision__gte=1),
            name="personal_os_revision_positive",
        ),
    ]
    constraints.extend(
        [
            models.CheckConstraint(
                condition=models.Q(**{f"{field_name}_state__in": VALUE_STATES}),
                name=f"personal_os_{field_name}_state_valid",
            )
            for field_name in (*SCALAR_SECTIONS, *LIST_SECTIONS)
        ]
    )
    constraints.extend(
        [
            models.CheckConstraint(
                condition=(
                    models.Q(**{f"{field_name}_state": "provided"})
                    & ~models.Q(**{f"{field_name}_value": ""})
                    | ~models.Q(**{f"{field_name}_state": "provided"})
                    & models.Q(**{f"{field_name}_value": ""})
                ),
                name=f"personal_os_{field_name}_value_state",
            )
            for field_name in SCALAR_SECTIONS
        ]
    )
    constraints.extend(
        [
            models.CheckConstraint(
                condition=(
                    models.Q(**{f"{field_name}_state": "provided"})
                    & models.Q(**{f"{field_name}_value__isnull": False})
                    | ~models.Q(**{f"{field_name}_state": "provided"})
                    & models.Q(**{f"{field_name}_value__isnull": True})
                ),
                name=f"personal_os_{field_name}_value_state",
            )
            for field_name in LIST_SECTIONS
        ]
    )
    return constraints


class Migration(migrations.Migration):
    dependencies = [
        ("growth", "0008_assessmentcontext_practicecontext"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalOSRevision",
            fields=[
                (
                    "stable_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contract_version",
                    models.CharField(
                        default="GG-PERSONAL-OS-1.0",
                        editable=False,
                        max_length=40,
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                *[
                    field
                    for section_id in SCALAR_SECTIONS
                    for field in (
                        (
                            f"{section_id}_state",
                            models.CharField(
                                choices=[
                                    ("unknown", "Unknown"),
                                    ("not_applicable", "Not applicable"),
                                    ("deferred", "Deferred"),
                                    ("provided", "Provided"),
                                ],
                                max_length=20,
                            ),
                        ),
                        (
                            f"{section_id}_value",
                            models.CharField(blank=True, default="", max_length=500),
                        ),
                    )
                ],
                *[
                    field
                    for section_id in LIST_SECTIONS
                    for field in (
                        (
                            f"{section_id}_state",
                            models.CharField(
                                choices=[
                                    ("unknown", "Unknown"),
                                    ("not_applicable", "Not applicable"),
                                    ("deferred", "Deferred"),
                                    ("provided", "Provided"),
                                ],
                                max_length=20,
                            ),
                        ),
                        (
                            f"{section_id}_value",
                            models.JSONField(blank=True, default=None, null=True),
                        ),
                    )
                ],
                ("canonical_snapshot", models.JSONField()),
                ("content_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_os_revisions",
                        to="growth.assessmentrun",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_os_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "personal_os_revision",
                "base_manager_name": "objects",
                "ordering": ["assessment_run_id", "revision"],
                "indexes": [
                    models.Index(
                        fields=["assessment_run", "-revision"],
                        name="personal_os_latest_idx",
                    )
                ],
                "constraints": _constraints(),
            },
        ),
    ]
