# Generated by Django 6.0.8 on 2026-08-27 14:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("growth", "0010_practicecheckin_typed_observations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyExecutionPlan",
            fields=[
                (
                    "stable_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "contract_version",
                    models.CharField(
                        default="GG-WEEKLY-EXECUTION-1.0", editable=False, max_length=40
                    ),
                ),
                ("week_start", models.DateField()),
                ("revision", models.PositiveIntegerField()),
                ("intended_on", models.DateField()),
                ("canonical_snapshot", models.JSONField()),
                ("content_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weekly_execution_plans",
                        to="growth.practiceaction",
                    ),
                ),
                (
                    "assessment_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_execution_plans",
                        to="growth.assessmentrun",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_execution_plans",
                        to="growth.practicesprint",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_execution_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["assessment_run_id", "week_start", "revision"],
            },
        ),
        migrations.CreateModel(
            name="WeeklyExecutionReview",
            fields=[
                (
                    "stable_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "contract_version",
                    models.CharField(
                        default="GG-WEEKLY-EXECUTION-1.0", editable=False, max_length=40
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("no_submitted_evidence", "No submitted evidence"),
                            ("attempted", "Attempted"),
                            ("completed", "Completed"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "next_step",
                    models.CharField(
                        choices=[
                            ("continue_current", "Continue the current action"),
                            ("plan_next_action", "Plan the next action"),
                            ("pause_reconsider", "Pause and reconsider"),
                            ("choose_different_practice", "Choose a different practice"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "adjustment",
                    models.CharField(
                        choices=[
                            ("none", "No adjustment"),
                            ("timing", "Change timing"),
                            ("scope", "Reduce or clarify scope"),
                            ("support", "Change support"),
                            ("context", "Change context"),
                            ("recovery", "Protect recovery or capacity"),
                        ],
                        max_length=20,
                    ),
                ),
                ("canonical_snapshot", models.JSONField()),
                ("content_hash", models.CharField(max_length=64)),
                ("submitted_at", models.DateTimeField()),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="growth.weeklyexecutionplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_execution_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["plan__week_start", "plan__revision"],
            },
        ),
        migrations.AddIndex(
            model_name="weeklyexecutionplan",
            index=models.Index(
                fields=["user", "-week_start", "-revision"], name="weekly_plan_latest_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklyexecutionplan",
            constraint=models.UniqueConstraint(
                fields=("assessment_run", "week_start", "revision"),
                name="unique_weekly_plan_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklyexecutionplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("contract_version", "GG-WEEKLY-EXECUTION-1.0")),
                name="weekly_plan_contract_v1",
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklyexecutionplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="weekly_plan_revision_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklyexecutionreview",
            constraint=models.CheckConstraint(
                condition=models.Q(("contract_version", "GG-WEEKLY-EXECUTION-1.0")),
                name="weekly_review_contract_v1",
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklyexecutionreview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("outcome__in", ["no_submitted_evidence", "attempted", "completed"])
                ),
                name="weekly_review_outcome_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklyexecutionreview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "next_step__in",
                        [
                            "continue_current",
                            "plan_next_action",
                            "pause_reconsider",
                            "choose_different_practice",
                        ],
                    )
                ),
                name="weekly_review_next_step_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklyexecutionreview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "adjustment__in",
                        ["none", "timing", "scope", "support", "context", "recovery"],
                    )
                ),
                name="weekly_review_adjustment_valid",
            ),
        ),
    ]
