# Generated by Django 6.0.8 on 2026-09-01 18:47

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("growth", "0011_weeklyexecutionplan_weeklyexecutionreview_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="practicesprint",
            name="scoring_contract_version",
            field=models.CharField(
                choices=[
                    ("GG-SCORE-STATE-1.0", "Historical event-level score state"),
                    (
                        "GG-COMPOSITE-CLOSEOUT-SCORING-1.0",
                        "Assessment composite and human closeout credit",
                    ),
                ],
                default="GG-SCORE-STATE-1.0",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="practicesprint",
            name="scoring_contract_version",
            field=models.CharField(
                choices=[
                    ("GG-SCORE-STATE-1.0", "Historical event-level score state"),
                    (
                        "GG-COMPOSITE-CLOSEOUT-SCORING-1.0",
                        "Assessment composite and human closeout credit",
                    ),
                ],
                default="GG-COMPOSITE-CLOSEOUT-SCORING-1.0",
                max_length=64,
            ),
        ),
        migrations.AddConstraint(
            model_name="practicesprint",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "scoring_contract_version__in",
                        [
                            "GG-SCORE-STATE-1.0",
                            "GG-COMPOSITE-CLOSEOUT-SCORING-1.0",
                        ],
                    )
                ),
                name="practice_sprint_scoring_contract_supported",
            ),
        ),
        migrations.CreateModel(
            name="CompletionCreditEvent",
            fields=[
                (
                    "stable_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("algorithm_version", models.CharField(max_length=64)),
                ("completed_action_ids", models.JSONField(default=list)),
                ("total_actions", models.PositiveSmallIntegerField()),
                ("minimum_completed", models.PositiveSmallIntegerField()),
                (
                    "completion_credit",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("source_snapshot", models.JSONField(default=dict)),
                ("source_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completion_credit_events",
                        to="growth.assessmentrun",
                    ),
                ),
                (
                    "competency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completion_credit_events",
                        to="growth.competency",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completion_credit_events",
                        to="growth.practiceprotocol",
                    ),
                ),
                (
                    "review",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completion_credit_event",
                        to="growth.practicereview",
                    ),
                ),
                (
                    "sprint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completion_credit_event",
                        to="growth.practicesprint",
                    ),
                ),
            ],
            options={
                "ordering": ["assessment_run_id", "created_at", "stable_id"],
            },
        ),
        migrations.CreateModel(
            name="CompositeAssessmentSnapshot",
            fields=[
                (
                    "stable_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("algorithm_version", models.CharField(max_length=64)),
                ("state_schema_version", models.CharField(max_length=64)),
                ("projection", models.JSONField(default=dict)),
                ("projection_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="composite_assessment_snapshot",
                        to="growth.assessmentrun",
                    ),
                ),
            ],
            options={
                "ordering": ["assessment_run_id"],
            },
        ),
        migrations.CreateModel(
            name="CompositeScoreSnapshot",
            fields=[
                (
                    "stable_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("initialize", "Initialize composite state"),
                            ("process", "Process completion closeout"),
                            ("reverse", "Reverse completion closeout"),
                            ("rebuild", "Repair composite state"),
                        ],
                        max_length=12,
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("algorithm_version", models.CharField(max_length=64)),
                ("state_schema_version", models.CharField(max_length=64)),
                ("before_state", models.JSONField(blank=True, default=dict)),
                ("after_state", models.JSONField(blank=True, default=dict)),
                ("active_event_count", models.PositiveIntegerField(default=0)),
                ("active_event_hash", models.CharField(max_length=64)),
                ("before_state_hash", models.CharField(max_length=64)),
                ("after_state_hash", models.CharField(max_length=64)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="composite_score_snapshots",
                        to="growth.assessmentrun",
                    ),
                ),
                (
                    "completion_credit_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="score_snapshots",
                        to="growth.completioncreditevent",
                    ),
                ),
            ],
            options={
                "ordering": ["assessment_run_id", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="CompositeScoreState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("algorithm_version", models.CharField(max_length=64)),
                ("state_schema_version", models.CharField(max_length=64)),
                ("state", models.JSONField(default=dict)),
                ("state_hash", models.CharField(max_length=64)),
                ("active_event_count", models.PositiveIntegerField(default=0)),
                ("active_event_hash", models.CharField(max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composite_score_state",
                        to="growth.assessmentrun",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composite_score_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["assessment_run_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="completioncreditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("minimum_completed__gt", 0),
                    ("total_actions__gte", models.F("minimum_completed")),
                ),
                name="completion_credit_threshold_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="completioncreditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("completion_credit__gte", 0), ("completion_credit__lte", 1)),
                name="completion_credit_in_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="compositescoresnapshot",
            constraint=models.UniqueConstraint(
                fields=("assessment_run", "sequence"), name="unique_composite_snapshot_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="compositescoresnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("operation", "initialize")),
                fields=("assessment_run",),
                name="unique_composite_state_initialization",
            ),
        ),
        migrations.AddConstraint(
            model_name="compositescoresnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("operation", "process")),
                fields=("completion_credit_event",),
                name="unique_completion_credit_processing",
            ),
        ),
        migrations.AddConstraint(
            model_name="compositescoresnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("operation", "reverse")),
                fields=("completion_credit_event",),
                name="unique_completion_credit_reversal",
            ),
        ),
        migrations.AddConstraint(
            model_name="compositescoresnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("completion_credit_event__isnull", False),
                        ("operation__in", ["process", "reverse"]),
                    ),
                    models.Q(
                        ("completion_credit_event__isnull", True),
                        ("operation__in", ["initialize", "rebuild"]),
                    ),
                    _connector="OR",
                ),
                name="composite_snapshot_event_matches_operation",
            ),
        ),
        migrations.AddConstraint(
            model_name="compositescoresnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("operation", "reverse"), _negated=True),
                    models.Q(("reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="composite_reversal_requires_reason",
            ),
        ),
    ]
