# Generated by Django 6.0.8 on 2026-09-02 20:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("growth", "0012_composite_closeout_scoring"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentCalibrationConsent",
            fields=[
                (
                    "stable_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contract_version",
                    models.CharField(
                        default="GG-ASSESSMENT-CALIBRATION-CONSENT-1.0",
                        editable=False,
                        max_length=64,
                    ),
                ),
                ("participant_token", models.UUIDField(editable=False)),
                ("revision", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[("consented", "Consented"), ("withdrawn", "Withdrawn")],
                        max_length=16,
                    ),
                ),
                ("canonical_snapshot", models.JSONField(default=dict)),
                ("content_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calibration_consents",
                        to="growth.assessmentrun",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_calibration_consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user_id", "assessment_run_id", "revision"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "assessment_run", "revision"),
                        name="unique_assessment_calibration_consent_revision",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("contract_version", "GG-ASSESSMENT-CALIBRATION-CONSENT-1.0")
                        ),
                        name="assessment_calibration_consent_contract_v1",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("revision__gt", 0)),
                        name="assessment_calibration_consent_revision_positive",
                    ),
                ],
            },
        ),
    ]
